### ISSUE TITLE
global Params

### ISSUE THREAD

**Issue by Barno** [FriendsOfSymfony/FOSUserBundle#1005]
Hi, i'd like use global params in my email

i set 

``` yaml
twig:
  # ......
    globals:
        barno: variabile globale
```

i'd like use this global inside FOSUserBundle.it.yml

``` yaml
# Registration
registration:
    check_email: Una mail è stata inviata a %email%. Contiene il link d'attivazione che devi utilizzare per attivare il tuo account.
    confirmed: Congratulazioni %username%, il tuo account è confermato.
    back: Torna alla pagina d'origine.
    submit: Registrazione
    flash:
        user_created: Utente creato con successo
    email:
        subject: Benvenuto %username%!
        message: |
            Ciao %username%!

            Per terminare la validazione del tuo account visita %confirmationUrl%

            Saluti,
            il Team.
            %barno%
            {%barno%}{{barno}}
```

but barno is not "parsed" thanks
