### ISSUE TITLE
customized login/logout json response

### ISSUE THREAD

**Issue by lukeman83** [FriendsOfSymfony/FOSUserBundle#1138]
Hi, 
I need to return a login/logout json response.

I customized my security.yml:

```
providers:
        fos_userbundle:
            id: fos_user.user_manager         
        webservice:
            id: my_provider
```

```
firewalls:
        app:
          pattern:   ^/app.*
          logout: true 
          security: true
          http_basic:             
            provider: webservice 
         main:
            pattern: ^/
            form_login:
                ...
```

my routing.yml

```
_login:
    pattern: /app_login
    defaults: {_controller: "projectMainBundle:AppSecurity:login", _format:json}
```

I will customize my AppSecurityController to return a json responde(access token).

How must I customize my config.yml?

```
    my_provider:      
         ....
```

I'm using doctrine db
