### ISSUE TITLE
Extending the extended User Class

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSUserBundle#1166]
I know it's possible to extend the BaseUser (in older versions of FOS and just the UserInterface in newer) when you create your own UserBundle in your vendor namespace.

Is it possible to extend that Extended User?

I understand that you have to specify the User Class in the fos_user config like this:

```
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Acme\UserBundle\Entity\AcmeUser
```

Will this still work if you extend  the AcmeUser?

For example, i'd like to keep different information for different roles in my application.

Employee extends AcmeUser
Intern extends AcmeUser

(I'm not talking about user roles but actual different attributes per user class)
