### ISSUE TITLE
Passwords are not cyphered (FOSUserBundle + MongoDB)

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSUserBundle#1212]
Passwords seem to be not cyphered when I use MongoDB.
I did every steps of this tutorial http://symfony.com/fr/doc/current/bundles/DoctrineMongoDBBundle/index.html

For example, if y retrieve Users objects (db.User.find()) : 

```
  { "_id" : ObjectId("51ebc30089a69c3802000001"), "username" : "user", 
 "usernameCanonical" : "user", "email" : "user@mail.com", "emailCanonical" : 
 "user@mail.com", "enabled" : false, "salt" : " ", 
 "password" : "password", "locked" : false, "expired" : false, "roles" : [ ], 
 "credentialsExpired" : false, "firstname" : "Firstname", "lastname" : "Lastname", 
 "birthday" : ISODate("2007-12-31T23:00:00Z"), "aboutMe" : "fzerfez", "isPublic" : true }
```

And this is my security.yml configuration : 

```
 security:
     encoders:
         Symfony\Component\Security\Core\User\User: sha512
         FOS\UserBundle\Model\UserInterface: sha512

     role_hierarchy:
         ROLE_ADMIN:       ROLE_USER
         ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN,       ROLE_ALLOWED_TO_SWITCH]

    providers:
         fos_userbundle:
             id: fos_user.user_provider.username
         in_memory:
             memory:
                 users:
                     user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                     admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
```
