### ISSUE TITLE
Remember me problem with Symfony 2.3.x

### ISSUE THREAD

**Issue by demos77** [FriendsOfSymfony/FOSUserBundle#1221]
Hi,

since the Symfony 2.3.x upgrade, the remember me checkbox don't work.
Before there are no problem.

Now i log in (with the checkbox checked), i kill the internet Navigator and when i relauch IE there is no auto-loggin.

In the security.yml i have

``` yaml
main:
            pattern: ^/
            anonymous: true
            form_login:
                provider: fos_userbundle
                login_path: ADWelcomeBundle_guest_homepage
                remember_me: true
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: ADWelcomeBundle_member_homepage
            remember_me:
                key: '%secret%'
                lifetime: 31536000
                path: /
                domain: ~
            logout:
                path: fos_user_security_logout
                target: ADWelcomeBundle_guest_homepage
```

And in my HomePageControler i check the user with

``` php
$user = $this->container->get('security.context')->getToken()->getUser();
if(!is_object($user)) ...
```
