### ISSUE TITLE
Service Registration for Overriden Form Type

### ISSUE THREAD

**Issue by rafaqf** [FriendsOfSymfony/FOSUserBundle#1328]
I'm trying to pass 2 parameters from my controller to a form that overrides the GroupFormType from the FUB. I need to show which roles has a group and also to be able to change them. Here's my Form.

```
    protected $roles;
    protected $groupRoles;

    public function __construct($roles, $groupRoles)
    {
        foreach ($roles as $role) {
            $theRoles[$role] = $role;
        }
        $this->roles = $theRoles;
        $this->groupRoles = $groupRoles;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder
        ->add('roles', 'choice', array(
                    'choices' => $this->roles,
                    'data' => $this->groupRoles,
                    'expanded' => true,
                    'multiple' => true,
                ))
                ->add('users', 'entity', array(
                    'class' => 'CosmosBundle:AdminUsers',
                    'label' => 'Users',
                    'property' => 'username',
                    'mapped' => false,
                    'expanded' => false,
                    'multiple' => true,
                ))
        ;
    }
```

The problem comes with the service registration, I'm having this exception: 
ServiceNotFoundException: The service "x_s_cosmos.group.form.type" has a dependency on a non-existent service "roles".

Here the code for the service:

```
    x_s_cosmos.group.form.type:
        class: X\S\CosmosBundle\Form\Type\GroupFormType
        arguments: ["@roles", "@groupRoles"]
        tags:
            - { name: form.type, alias: cosmos_group_form }
```

Arguments contains per default the FUB group class, but as I have redefined the constructor, I thought it should work.

What is it wrong there???

Thanks a lot in advance.
