### ISSUE TITLE
Add setter for property class in RegistrationFormType

### ISSUE THREAD

**Issue by L0rD59** [FriendsOfSymfony/FOSUserBundle#1331]
Would it be possible to add a setter for class property in RegistrationFormType for inheritance service.

My use case : 

```
services:
    lig_user_form_entity_user_registration:
        class: LIG\Bundle\UserBundle\Form\Entity\User\RegistrationFormType
        parent: fos_user.registration.form.type
        arguments: [ @request, @router]
        calls:
            - [setClass, ['LIG\Bundle\UserBundle\Entity\User']]
        scope: request
        tags:
            - { name: form.type, alias: lig_user_form_entity_user_registration }

    lig_user_form_entity_user_administrator_registration:
        class: LIG\Bundle\UserBundle\Form\Entity\User\Administrator\RegistrationFormType
        parent: lig_user_form_entity_user_registration
        arguments: [ ]
        calls:
            - [setClass, ['LIG\Bundle\UserBundle\Entity\UserAdministrator']]
        scope: request
        tags:
            - { name: form.type, alias: lig_user_form_entity_user_administrator_registration }
```

thx for replies
