### ISSUE TITLE
No error message shown when cookies are disabled

### ISSUE THREAD

**Issue by flip111** [FriendsOfSymfony/FOSUserBundle#1428]
When the client doesn't have cookies disabled no warning message is shown. Expected message: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/AbstractAuthenticationListener.php#L142

Some assumptions i've made:
No session can be started without cookie support.
Redirect serves a fresh page, so the only way to show this error message is to do a forward.

My setup

``` yml
firewalls:
        main:
                pattern: ^/
                form_login:
                        provider: fos_userbundle
                        csrf_provider: form.csrf_provider
                        default_target_path: /%locale%/saved-reports
                        login_path:     /%locale%/
                        check_path:     fos_user_security_check
                        failure_forward: true
                        failure_path: /%locale%/
                logout:
                        path: fos_user_security_logout
                        target: /
                anonymous:    true
```

In my own controller:

``` php
<?php
public function homeAction(Request $request) {
    $error = $request->attributes->get('_security.last_error');
    if (is_object($error)) {
        $error = $error->getMessage();
    } else {
        $error = var_export($error, true);
    }

    // .. some more stuff
}
```

The error is available in this controller!

In `base.html.twig`: `{{ render(controller('FOSUserBundle:Security:Login')) }}`

FOS User Bundle tries to grab the error from the request here https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/SecurityController.php#L27 but since i render from base.html.twig it's not the right request anymore but a sub-request??

I placed debug points all over (like HttpKernel) but i don't understand why this doesn't work. Perhaps the process can be simplified with the RequestStack.

Also as alternative i tried passing the error variable like this `{{ render(controller('FOSUserBundle:Security:Login', {'error' : error})) }}` and then catching it in the SecurityController like this `public function loginAction(Request $request, $error) {` but that didn't relay the error either.
