### ISSUE TITLE
Could not load type "kyna_user_registration" 

### ISSUE THREAD

**Issue by AxelBriche** [FriendsOfSymfony/FOSUserBundle#1443]
Hello, My error:  Could not load type "kyna_user_registration".

I have this config:

RegistrationFormType.php
    <?php

```
namespace Kyna\UserBundle\Form\Type;

use Symfony\Component\Form\FormBuilderInterface;
use FOS\UserBundle\Form\Type\RegistrationFormType as BaseType;

class RegistrationFormType extends BaseType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        // add your custom field
        $builder->add('usernameInGame');
    }

    public function getName()
    {
        return 'kyna_user_registration';
    }
}
```

config.yml

```
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Kyna\UserBundle\Entity\User
    registration:
        form:
            type: kyna_user_registration
```

services.yml

```
services:
    kyna_user.registration.form.type:
        class: Kyna\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: kyna_user_registration }
```

And I have this error:  Could not load type "kyna_user_registration".
I use FosUserBundle 2.3.3, have you a solution for this problem please ? Thanks.
