### ISSUE TITLE
UniqueEntity throws an exception but confirmation email is sent anyway

### ISSUE THREAD

**Issue by bajalovic** [FriendsOfSymfony/FOSUserBundle#1501]
I have two problems actually. First one is that I keep getting SQL exception on a field where I set unique=true. 

```
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity("mobile_number")
 */
class User extends BaseUser
{

    /**
     * @ORM\Column(length=13, unique=true)
     *
     * @Assert\NotBlank(message="Please enter your phone number", groups={"Registration", "Profile"})
     * @Assert\Length(
     *  min=9,
     *  max=13,
     *  minMessage="The phone number is too short.",
     *  maxMessage="The phone number is too long.",
     *  groups={"Registration", "Profile"}
     *  )
     */
    protected $mobile_number;
...
```

I also tried all the variations on setting UniqueEntity (@UniqueEntity(fields={"mobile_number"}), with groups, with message etc.. I also tried with setting constraint via .yml file but I still keep getting an exception and not the message. 

And even when I get an exception that there is already entered mobile number in database, confirmation email is sent anyway. 

I added mobile_number field into `services.yml` via: 

```
services:
    esse_works_user.registration.form.type:
        class: EsseWorks\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: esseworks_user_registration }
```

And `RegistrationFormType`:

```
class RegistrationFormType extends BaseType {
    public function buildForm(FormBuilderInterface $builder, array $options) {
        parent::buildForm($builder, $options);

        $builder->add('mobile_number');
    }

    public function getName() {
        return 'esseworks_user_registration';
    }
}
```

Another odd thing is that `Entity\User.php` file (in PhpStorm) display message that `use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;` is not used. But few lines below I have `@UniqueEntity` annotation?!

Edit: I am using "friendsofsymfony/user-bundle": "~2.0@dev"
