### ISSUE TITLE
Error on updating schema with overridden base user

### ISSUE THREAD

**Issue by drgomesp** [FriendsOfSymfony/FOSUserBundle#1503]
I'm having this error when trying to update the schema:

```
 [Doctrine\Common\Persistence\Mapping\MappingException]                                           
  Invalid mapping file 'FOS.UserBundle.Model.User.orm.xml' for class 'FOS\UserBundle\Model\User'.  
```

My configuration uses annotations, out of the bundle structure, as you can see here:

``` yml
ppings:
    model:
        type: annotation
        dir: "%kernel.root_dir%/../src/MyApp/Entity"
        prefix: MyApp\Entity
        alias: Entity
        is_bundle: false
    FOSUserBundle:
        type: xml
        dir: '%kernel.root_dir%/../vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Resources/config/doctrine'
        prefix: FOS\UserBundle\Model
        is_bundle: false # needed as we don't follow the standard convention for bundles
```

Also, if I don't include this mapping from FOSUserBundle, my table does not get the base class fields, only the ones have on the parent class.

What am I missing?
