### ISSUE TITLE
problem creating user when using a chain provider

### ISSUE THREAD

**Issue by PrinceAnsong** [FriendsOfSymfony/FOSUserBundle#1508]
When using only one Doctrine user manager, I can access it by fetching it from the service container using the `fos_user.user_manager` key and then call `createUser()` to create a user.

However, I now have a chain provider.

``` yaml
# app/config/security.yml
security:
    # ...
    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    john: { password: johnspassword, roles: [ ROLE_USER ] }
```

Fetching `fos_user.user_manager` from the service container now returns a `Symfony\Component\Security\Core\User\ChainUserProvider` instance.

I could create the user and persist it manually but I think it would be cleaner to use the user manager. Is there a way I can still reach my Doctrine user manager to create users?

Thanks.
