### ISSUE TITLE
Can't get "Registration Confirmation" works

### ISSUE THREAD

**Issue by reypm** [FriendsOfSymfony/FOSUserBundle#1536]
I'm trying to get "Registration Confirmation" working on my application but can't. Since I need to set some fields on profiles and so on this is how my method `save` for users is:

```
public function saveAction(Request $request)
{
    $em = $this->getDoctrine()->getManager();

    $userManager = $this->container->get('fos_user.user_manager');
    $user = $userManager->createUser();

    $entityProfile = new SysPerfil();
    $formProfile = $this->createForm(new PerfilType(), $entityProfile);
    $formProfile->handleRequest($request);

    $user_data = $request->get('user_profile');

    if ($formProfile->isValid()) {
        $role = $request->get('user_profile')['roleType'];

        $user->setUsername($user_data['rif']);
        $user->setEmail($user_data['user']['email']);
        $user->setPlainPassword($user_data['user']['password']);

        if ($role === "O") {
            $user->addRole("ROLE_OPERADOR");
        }
        elseif ($role === "CH") {
            $user->addRole("ROLE_CENTRO_HIPICO");
        }

        $userManager->updateUser($user);

        $entityProfile->setUser($user);
        $em->persist($entityProfile);
        $em->flush();

        $this->_authenticateAccount($user);

        return $this->redirect($this->generateUrl('datos-basicos'));
    }
    else {
        $errors = $this->getFormErrors($formProfile);
    }

    return new JsonResponse(array('status' => true, 'errors' => $errors));
}
```

And this is what I've configured at `config.yml` file:

```
# FOSUserBundle
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: Sunahip\UserBundle\Entity\SysUsuario
    group:
        group_class: Sunahip\UserBundle\Entity\SysGrupos
    registration:
        confirmation:
            enabled:    true
```

What is wrong there?
