### ISSUE TITLE
unable to access after login 

### ISSUE THREAD

**Issue by devswaam** [FriendsOfSymfony/FOSUserBundle#1538]
After creating user and login , i got this error 
You must configure the check path to be handled by the firewall using form_login in your security firewall configuration.

searched to solve this but couldn't not. help please...
here is my security.yml file

```
          security:
          #    providers:
          #        in_memory:
          #            memory: ~

              firewalls:
                  dev:
                      pattern: ^/(_(profiler|wdt)|css|images|js)/
                      security: false

                  default:
                      anonymous: ~

                  main:
                      pattern: ^/
                      form_login:
                           provider: fos_userbundle
                           csrf_provider: form.csrf_provider
                      logout:       true
                      anonymous:    true

              encoders:
                      FOS\UserBundle\Model\UserInterface: sha512

              role_hierarchy:
                      ROLE_ADMIN:       ROLE_USER
                      ROLE_SUPER_ADMIN: ROLE_ADMIN

              providers:
                      fos_userbundle:
                          id: fos_user.user_provider.username

              access_control:
                      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
                      - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
                      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
                      - { path: ^/admin/, role: ROLE_ADMIN }
```

here is routing.yml

```
      swaam_patient:
          resource: "@swaamPatientBundle/Resources/config/routing.yml"
          prefix:   /
      admin:
          resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
          prefix: /admin

      _sonata_admin:
          resource: .
          type: sonata_admin
          prefix: /admin

      fos_user_security:
          resource: "@FOSUserBundle/Resources/config/routing/security.xml"

      fos_user_profile:
          resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
          prefix: /profile

      fos_user_register:
          resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
          prefix: /register

      fos_user_resetting:
          resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
          prefix: /resetting

      fos_user_change_password:
          resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
          prefix: /profile
```

**Comment by SteaveAshmore** [comment]
same issue any guide?

**Comment by allabakash** [comment]
Hi, i have updated SF 2.4 to SF 2.8 and Updated FOSUserBundle 1.4 to 2.0 version
Below attachment is my security.yml file
![security yml](https://user-images.githubusercontent.com/932164/31877041-9ce29962-b7f2-11e7-8247-8d53614c9256.png)

Showing below RunTimeException
![runtimeexception](https://user-images.githubusercontent.com/932164/31877109-e3dbc866-b7f2-11e7-9e50-2bc477481c4e.png)

It was working fine with my SF2.4 version.

I may have missed something, please help.

**Comment by shakaran** [comment]
@allabakash If you use the value _fos_user_security_check_ you are calling to _SecurityController.php_ class and invoking the _checkAction()_ method which exactly only throws an RuntimeError Exception with the error displayed "You must configure the check path to be handled by the firewall using form_login in your security firewall configuration.". So the fix is so simple that not use the value fos_user_security_check and implement your authentication listener.

So @stof the users are not fully understanding that they don't have to use the default SecurityController::checkAction() for this and they have to especify another with an authentication listener.

**Comment by allabakash** [comment]
Thanks for your reply,
Still the same, without fos_user_security_check.
Security.yml
![security](https://user-images.githubusercontent.com/932164/31935633-effa239c-b8cc-11e7-8a71-cbbe63ba6e1c.png)

now it's pointing to RuntimeException: You must configure the check path to be handled by the firewall using form_login in your security firewall configuration. in /var/www/html/Soundbasics_production/SoundBasics_Symfony/vendor/friendsofsymfony/user-bundle/Controller/SecurityController.php on line 78
![1](https://user-images.githubusercontent.com/932164/31935677-0e805070-b8cd-11e7-86db-c674e22c3be8.png)
@stof @shakaran 
please help me to fix this issue, struggling from past 3 days.

**Comment by shakaran** [comment]
@allabakash after change that, you need implement a authentication listener, for example:

I have this under _src/MyAppBundle/EventListener/AuthenticationListener.php_

```php
<?php

/*
 * This file is part of the FOSUserBundle package.
 *
 * (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace FOS\UserBundle\EventListener;

use FOS\UserBundle\Event\FilterUserResponseEvent;
use FOS\UserBundle\Event\UserEvent;
use FOS\UserBundle\FOSUserEvents;
use FOS\UserBundle\Security\LoginManagerInterface;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Security\Core\Exception\AccountStatusException;

class AuthenticationListener implements EventSubscriberInterface
{
    /**
     * @var LoginManagerInterface
     */
    private $loginManager;

    /**
     * @var string
     */
    private $firewallName;

    /**
     * AuthenticationListener constructor.
     *
     * @param LoginManagerInterface $loginManager
     * @param string                $firewallName
     */
    public function __construct(LoginManagerInterface $loginManager, $firewallName)
    {
        $this->loginManager = $loginManager;
        $this->firewallName = $firewallName;
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return array(
            FOSUserEvents::REGISTRATION_COMPLETED => 'authenticate',
            FOSUserEvents::REGISTRATION_CONFIRMED => 'authenticate',
            FOSUserEvents::RESETTING_RESET_COMPLETED => 'authenticate',
        );
    }

    /**
     * @param FilterUserResponseEvent  $event
     * @param string                   $eventName
     * @param EventDispatcherInterface $eventDispatcher
     */
    public function authenticate(FilterUserResponseEvent $event, $eventName, EventDispatcherInterface $eventDispatcher)
    {
        try {
            $this->loginManager->logInUser($this->firewallName, $event->getUser(), $event->getResponse());

            $eventDispatcher->dispatch(FOSUserEvents::SECURITY_IMPLICIT_LOGIN, new UserEvent($event->getUser(), $event->getRequest()));
        } catch (AccountStatusException $ex) {
            // We simply do not authenticate users which do not pass the user
            // checker (not enabled, expired, etc.).
        }
    }
}
```
In _services.yml_:

```yaml
services:
    account.security_listener:
        class: %account.security_listener.class%
        arguments: ['@security.authorization_checker', '@session'] # security.context (deprecated) or 'security.token_storage
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin 
```

Then as _src/MyAppBundle/Controller/SecurityController.php_:

```php
<?php

namespace MyAppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class SecurityController extends Controller
{
    public function loginAction(Request $request)
    {
        /** @var $session Session */
        $session = $request->getSession();

        $authenticationUtils = $this->get('security.authentication_utils');
        
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();
        
        $csrfToken = $this->has('security.csrf.token_manager')
        ? $this->get('security.csrf.token_manager')->getToken('authenticate')->getValue()
        : null;
        
        $authChecker = $this->get('security.authorization_checker');
        $router = $this->get('router');

        return $this->render(
                'FOSUserBundle:Security:login.html.twig',
                [
                    // last username entered by the user
                    'last_username' => $lastUsername,
                    'error'         => $error,
                    'csrf_token' => $csrfToken,
                ]
                );
    }
}
```
