### ISSUE TITLE
when not used with email it should turn off the dependency on mailer

### ISSUE THREAD

**Issue by cordoval** [FriendsOfSymfony/FOSUserBundle#1561]
``` bash
 [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "fos_user.mailer" has a dependency on a non-existent service "mailer".
```

**Comment by crmpicco** [comment]
If you have a custom Mailer service you would register it like this:
 
```
# app/config/config.yml
fos_user:
    # ...
    service:
        mailer: app.custom_fos_user_mailer
```
