### ISSUE TITLE
MappingException error on setting up FOSUserBundle

### ISSUE THREAD

**Issue by CrossUp** [FriendsOfSymfony/FOSUserBundle#1567]
After doing everything step-by-step as shown in [Instructions](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/index.md) I received MappingException error on step 7 when tried to update my database. Thereafter i got that error everywhere (even on php app/console router:debug). The problem is that "non existing" class DO exist.

``` <?php
namespace project\ModelBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * super_admin
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class super_admin extends BaseUser
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=50)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=50)
     */
    private $lastname;

    /**
     * @var string
     *
     * @ORM\Column(name="abriev", type="string", length=10)
     */
    private $abriev;

    /**
     * @var boolean
     *
     * @ORM\Column(name="isAuth", type="boolean")
     */
    private $isAuth;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     *
     * @var string 
     * 
     * @ORM\Column(name="admin_abriev", type="string", length=10, nullable=true)
     */
    private $admin_abriev;
}
```

My app/config/config.yml

```
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: project\ModelBundle\Entity\super_admin
```

My project/ModelBundle/Resources/config/doctrine/super_admin.orm.yml

```
project\ModelBundle\Entity\super_admin:
    type:  entity
    table: super_admin
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
```

Steps 4 and 6 i just copied to my project, didnt change anything. I have went thru the manual like 6 times already and cant find a mistake, please give some information.
