### ISSUE TITLE
[DX] Simplify the step 6 of the installation process

### ISSUE THREAD

**Issue by javiereguiluz** [FriendsOfSymfony/FOSUserBundle#1578]
I know that because of the nature of this bundle, its installation cannot be neither easy nor immediate. However, we could think of changes to simplify a bit the 7-step installation.

I'm thinking about [the Step 6](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/index.md#step-6-import-fosuserbundle-routing-files), which states that you have to import all these routing resources from your application:

``` yaml
# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
```

**My question** is: couldn't the bundle load its routes automatically and only force the user to configure the paths if he/she wants to change them? Or would that be even worse than the current situation? Any other idea to simplify this or any of the other six installation steps?
