### ISSUE TITLE
Problem overriding form

### ISSUE THREAD

**Issue by Luvelnet** [FriendsOfSymfony/FOSUserBundle#1580]
Hi guys!

I'm trying to override a profile/registration form but it throw this:

```
 FatalErrorException: Error: Class 'MyUserBundle\Form\Type\RegistrationFormType' not found in /home/guest/Projects/My/app/cache/dev/appDevDebugProjectContainer.php line 1586
```

The code is:

**RegistrationFormType**

``` php
<?php

namespace MyUserBundle\Form\Type;

use Symfony\Component\Form\FormBuilderInterface;
use FOS\UserBundle\Form\Type\RegistrationFormType as BaseType;

class RegistrationFormType extends BaseType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       parent::buildForm($builder, $options);

        // add your custom field
        $builder->add('name');
    }

    public function getName()
    {
        return 'my_user_registration';
    }
}
```

**Services.yml**

``` yaml
services:
    my_user.registration.form.type:
        class: MyUserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: my_user_registration }
```

**Config.yml**

``` yaml
    registration:
        confirmation:
            enabled: true
        form:
            type: my_user_registration 
```

**Important:** I have already clear cache. 

Any suggestion?

Thanks!
