### ISSUE TITLE
You must configure the check path to be handled by the firewall

### ISSUE THREAD

**Issue by pinouf** [FriendsOfSymfony/FOSUserBundle#1605]
hello,
Can you help me .. ?
I think it is a stupid error but i dont find the problem...

i go to http://localhostprout/toto/login , i enter login et password and message " You must configure the check path to be handled by the firewall using form_login in your security firewall configuration "
I have probem with logout too

thank YOU !! 

``` yaml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        #oauth:
            #id: my_oauth_members
        hwi:                               
            id: hwi_oauth.user.provider

        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    facebook:           "/tata/check-facebook"
                    google:             "/tata/check-google"
                login_path:        /tata
                use_forward:       false
                failure_path:      /tata
                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity

        main:
            pattern: ^/toto
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /toto
            logout:       true
            anonymous:    true




    access_control:
        - { path: ^/toto/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tata, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ˆ/oauth/target, roles: ROLE_OAUTH_USER }
        - { path: ˆ/oauth/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
```

routing.yml

``` yaml
oauth_register:
    pattern: /oauthRegister
    defaults: { _controller: AcmeMainBundle:Security:oauthRegister }


hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /tata


facebook_login:
    pattern: /tata/check-facebook

google_login:
    pattern: /tata/check-google

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /toto
```
