### ISSUE TITLE
security.login.username and security.login.password not translated

### ISSUE THREAD

**Issue by webdevilopers** [FriendsOfSymfony/FOSUserBundle#1607]
As opposed to the closed issue https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1174 I am not using a custom login page just the regular template:

``` twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% if error %}
    <div>{{ error|trans({}, 'FOSUserBundle') }}</div>
{% endif %}

<form action="{{ path("fos_user_security_check") }}" method="post">
    <input type="hidden" name="_csrf_token" value="{{ csrf_token }}" />

    <label for="username">{{ 'security.login.username'|trans({}, 'FOSUserBundle') }}</label>
    <input type="text" id="username" name="_username" value="{{ last_username }}" required="required" />

    <label for="password">{{ 'security.login.password'|trans({}, 'FOSUserBundle') }}</label>
    <input type="password" id="password" name="_password" required="required" />

    <input type="checkbox" id="remember_me" name="_remember_me" value="on" />
    <label for="remember_me">{{ 'security.login.remember_me'|trans({}, 'FOSUserBundle') }}</label>

    <input type="submit" id="_submit" name="_submit" value="{{ 'security.login.submit'|trans({}, 'FOSUserBundle') }}" />
</form>
{% endblock fos_user_content %}
```

Comparing to this code:
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/views/Security/login.html.twig
my template seems to be out of date so I have updated it.

My config:

``` yaml
framework:
    default_locale: de
    translator:      { fallback: "%locale%" }

services:
    twig.extension.intl: 
        class: Twig_Extensions_Extension_Intl 
        tags: 
            - { name: twig.extension }  

parameters:
    locale: de
```

The default translations:
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/translations/FOSUserBundle.de.yml

For some reasons `security.login.username`  and `security.login.password` are still not translated:
![bildschirmfoto vom 2014-09-22 12 27 43](https://cloud.githubusercontent.com/assets/3479626/4354856/f5026b82-4242-11e4-9c1e-64b0cbcae27c.png)

I made some changes to the `security.login.submit` and it worked fine. Maybe some problems with quotes `"`?
