### ISSUE TITLE
Two firewalls - wrong redirection

### ISSUE THREAD

**Issue by deyvid5** [FriendsOfSymfony/FOSUserBundle#1634]
Hello,
I have problem with configuring two firewalls in my app based on Symfony2 with the use of FosUserBundle. What I want to have is, secured area for customer on my webiste, at the front level, and secured area for backend. What I had managed to do is, that I really do have two sections (/shop) and (/admin) and so far they're working but the problem is, that even when I log in on the shop form or admin form it keeps redirecting me to the same direction (/).

It's my security.yml:

``` yaml
jms_security_extra:
    secure_all_services: false
    expressions: true

security:
  encoders:
    FOS\UserBundle\Model\UserInterface: sha512

  role_hierarchy:
    ROLE_CUSTOMER:    ROLE_USER
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    fos_userbundle:
        id: fos_user.user_provider.username

  firewalls:
    admin_secured:
        context: site
        pattern: ^/admin/
        form_login:
          provider: fos_userbundle
          csrf_provider: form.csrf_provider
          use_referer:    true
          always_use_default_target_path: true
          default_target_path: /admin/
          login_path: /login
          check_path: /admin/login_check
        logout:
          path:   /admin/logout
        anonymous: false
    main:
        context: site
        pattern: ^/
        form_login:
          provider: fos_userbundle
          csrf_provider: form.csrf_provider
          default_target_path: /
          target_path_parameter: redirect_url
          login_path: frd_login
        logout:
          path:   fos_user_security_logout
          target: frd_home
        anonymous:    true

  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/shop/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/shop/, role: ROLE_USER }
    - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
```

And chunk of my config.yml:

``` yaml
fos_user:
  db_driver: propel
  firewall_name: main 
  user_class: FOS\UserBundle\Propel\User
  group:
    group_class: FOS\UserBundle\Propel\Group
```

Again, when I log in on the /admin or /shop (<- it is for customers) it's redirecting me to the home (/) but from the config I assue that in the admin section it should redirect me to /admin/ and in the shop section to the / like it does for every case.

Need some help. Haven't I missed something?

**Comment by AndrewCarterUK** [comment]
@deyvid5 - did you ever solve this? I have the same thing

**Comment by deyvid5** [comment]
@AndrewCarterUK Unfortunately not. Still having this issue, and it seems nobody know what is wrong.

**Comment by AndrewCarterUK** [comment]
Just fixed it, mine wasn't an issue with multiple firewalls - the problem was that session files were not being stored.

I only had an issue when I deployed to a VPS (worked fine locally) and running it in 'dev' mode on production VPS showed that there was a permissions issue reading PHP session files. Pretty much this:

http://www.inanzzz.com/index.php/post/7n5w/symfony2-warning-sessionhandler-read-open-var-lib-php5-sessions-sess-failed-permission-denied

**Comment by MarwenBenTalebAli** [comment]
Hello,
I have two users, one is 'Candidat' and the other is 'Recruteur'.
Im getting this error when tring to connect with the user 'Recruteur'

**You must configure the check path to be handled by the firewall using form_login in your security firewall configuration.**

 i have problem with the pattern: ^/recruteur$ and ^/

```
        firewall_recruteur:
            pattern: ^/recruteur$
            form_login:
                  provider: fos_userbundle
                  csrf_token_generator: security.csrf.token_manager
                  login_path: fos_recruteur_user_security_login
                  check_path: fos_recruteur_user_security_check
                  remember_me: true
                  # login success redirecting options (read further below)
                  always_use_default_target_path: true
                  default_target_path: mon_espace_recruteur
                  target_path_parameter:          _target_path
                  use_referer:                    false
            logout:
                  path:   fos_recruteur_user_security_logout
                  target: fos_recruteur_user_security_login
            anonymous: true
            remember_me:
                   secret: '%secret%'
            guard:
                authenticators:
                    - app.security.login_form_authenticator

        firewall_candidat:
            pattern: ^/
            form_login:
                  provider: fos_userbundle
                  csrf_token_generator: security.csrf.token_manager
                  login_path: fos_user_security_login
                  check_path: fos_user_security_check
                  remember_me: true
                  # login success redirecting options (read further below)
                  always_use_default_target_path: true
                  default_target_path:            mon_espace_candidat
                  target_path_parameter:          _target_path
                  use_referer:                    false
            logout:
                  path:   fos_user_security_logout
                  target: fos_user_security_login
            anonymous:   true
            remember_me:
                   secret: '%secret%'
            guard:
                authenticators:
                    - app.security.login_form_authenticator

    access_control:
            # Accès à autoriser pour la connexion au FrontOffice
            - { path: ^/[a-z][a-z]/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[a-z][a-z]/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[a-z][a-z]/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            #recruteur
            - { path: ^/[a-z][a-z]/recruteur/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[a-z][a-z]/recruteur/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[a-z][a-z]/recruteur/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[a-z][a-z]/recruteur/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            # Accès à autoriser pour la connexion au BackOffice
            - { path: ^/admin/[a-z][a-z]/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            # Protection du Backoffice en sécurisant les liens admin
            - { path: /admin, role: ROLE_MODERATOR }
```

The file routing_candidat.yml:
```
fos_user_security_login:
    path:      /candidat/login
    defaults:  { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path: /candidat/check
    defaults: { _controller: FOSUserBundle:Security:check, _method: POST }

fos_user_security_logout:
    path: /candidat/logout
    defaults: { _controller: FOSUserBundle:Security:logout }
```

The file routing_recruteur.yml :

```
fos_recruteur_user_security_login:
    path:      /recruteur/login
    defaults:  { _controller: FOSUserBundle:Security:login }
    #FOSUserBundle:Security:login

fos_recruteur_user_security_check:
    path:      /recruteur/check
    defaults: { _controller: FOSUserBundle:Security:check, _method: POST }
    #FOSUserBundle:Security:check

fos_recruteur_user_security_logout:
    path: /recruteur/logout
    defaults: { _controller: FOSUserBundle:Security:logout }
```

The file routing.yml:

```
route_recruteur:
   resource: 'routing_recruteur.yml'

route_candidat:
   resource: 'routing_candidat.yml'
```
