### ISSUE TITLE
Reflection Exception Property sava\UserBundle\Entity\User Tickets does not exist

### ISSUE THREAD

**Issue by piux** [FriendsOfSymfony/FOSUserBundle#1670]
im trying to link my user table to another table and changed the orms, for some reason whenever i use `php app/console doctrine:schema:update --dump-sql` it gives me this error:  

```
[ReflectionException]
Property sava\UserBundle\Entity\User::$Tickets does not exist
```

usually i first create the orm and then generate with doctrine:generate:entities, my problem is whenever im trying to update the schema, it gives me this error, i have already tried:
1. clear doctrine cache with php app/console doctrine:cache:clear-query, clear mapping, ect.
2. manually deleting the cache folder.
3. deleting ticket entity and generating them again.
4. setting all the fields to protected.

i dont think is doctrine causing the issue, any ideas?

error this are my dependencys.

User.Orm:

```
sava\UserBundle\Entity\User:
    type: entity
    table: User
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        nombreCliente:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: nombre_cliente
        rifCedula:
            type: string
            length: 40
            fixed: false
            nullable: false
            column: rif_cedula
        telefono:
            type: string
            length: 30
            fixed: false
            nullable: true
        celular:
            type: string
            length: 30
            fixed: false
            nullable: true
        direccion:
            type: string
            length: 250
            fixed: false
            nullable: true
    oneToMany:
        Tickets:
            targetEntity: sava\SoporteBundle\Entity\TblTicket
            mappedBy: idUser
            cascade: ["persist", "remove"]
    lifecycleCallbacks: {  }
```

Ticket.Orm.

```
sava\SoporteBundle\Entity\TblTicket:
    type: entity
    table: tbl_ticket
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        titulo:
            type: string
            length: '80'
        contenido:
            type: text
        isClosed:
            type: boolean
        fecha:
            type: date
    oneToMany:
        respuestas:
            targetEntity: sava\SoporteBundle\Entity\TblRespuesta
            mappedBy: ticket
            cascade: ["persist", "remove"]
    oneToOne:
        idUser:
            targetEntity: sava\UserBundle\Entity\User
            inversedBy: Tickets
            #nullable: true
            joinColumn:
                name: id_user
                referencedColumnName: id
    lifecycleCallbacks: {  }
```

Ticket entity(deleted some unrelated fields for clarity):

```
<?php

namespace sava\SoporteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * TblTicket
 */
class TblTicket
{
    /**
     * @var integer
     */
    private $id;


    /**
     * @var \Doctrine\Common\Collections\Collection
     */

        public function __construct()
    {
        $this->respuestas = new \Doctrine\Common\Collections\ArrayCollection();
    }

    protected $idUser;

        public function setIdUser(\sava\UserBundle\Entity\User $idUser = null)
    {
        $this->idUser = $idUser;

        return $this;
    }

    /**
     * Get idUser
     *
     * @return \sava\UserBundle\Entity\User 
     */
    public function getIdUser()
    {
        return $this->idUser;
    }
}
>
```

this is my ticket entity extended by fos/user/bundle (some fields where deleted for clarity):
    <?php
    // src/sava/UserBundle/Entity/User.php

```
namespace sava\UserBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;


/**
 * user
 *
 */
class User extends BaseUser
{
    public function __construct()
    {
        parent::__construct();
        //$this->User = new \Doctrine\Common\Collections\ArrayCollection();

    }



    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $Tickets;


    /**
     * Add Tickets
     *
     * @param \sava\SoporteBundle\Entity\TblTicket $tickets
     * @return User
     */
    public function addTicket(\sava\SoporteBundle\Entity\TblTicket $tickets)
    {
        $this->Tickets[] = $tickets;

        return $this;
    }

    /**
     * Remove Tickets
     *
     * @param \sava\SoporteBundle\Entity\TblTicket $tickets
     */
    public function removeTicket(\sava\SoporteBundle\Entity\TblTicket $tickets)
    {
        $this->Tickets->removeElement($tickets);
    }

    /**
     * Get Tickets
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTickets()
    {
        return $this->Tickets;
    }
}
```
