### ISSUE TITLE
REGISTRATION_SUCCESS setResponse not working with email confirmation

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfSymfony/FOSUserBundle#1799]
Having the following configuration:

``` yaml
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    use_username_form_type: false
    service:
        mailer: mailer.user
    registration:
        form:
            type: user_registration
        confirmation:
            enabled: true
    profile:
        form:
            type: user_profile
```

And the following Listener:

``` php
<?php

namespace AppBundle\Listener;

use FOS\UserBundle\Event\FormEvent;
use FOS\UserBundle\FOSUserEvents;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\Response;

/**
 * Class FOSUserListener
 */
class FOSUserListener implements EventSubscriberInterface
{
    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return [
            FOSUserEvents::REGISTRATION_SUCCESS     => 'onRegistrationSuccess',
        ];
    }

    /**
     * @param FormEvent $event
     */
    public function onRegistrationSuccess(FormEvent $event)
    {
        $event->setResponse(new Response('OK'));
    }
}
```

I should get a simple 'OK' response after registration success, but got the default checkEmail redirection instead.

Seems my event is overridden by the vendor, isn't it?

Using the fos-user:

```
$ composer info -i | grep user
friendsofsymfony/user-bundle             dev-master 808672b Symfony FOSUserBundle
```
