### ISSUE TITLE
Overriding Registration Handler

### ISSUE THREAD

**Issue by jayesbe** [FriendsOfSymfony/FOSUserBundle#1830]
Ive been at this for 3 days. How exactly do you override the registration handler ?

config.yml
```
fos_user:
    registration:
        form:
            type:               acme_user_registration
            name:               acme_user_registration_form
            handler:            acme_user.registration.form.handler
            validation_groups:  [Registration, Default]
```

RegistrationController.php (custom)
```
class RegistrationController extends BaseController
{
    public function registerAction()
    {
        $userManager = $this->container->get('fos_user.user_manager');

        $form = $this->container->get('fos_user.registration.form');
        $formHandler = $this->container->get('fos_user.registration.form.handler');
        $confirmationEnabled = $this->container->getParameter('fos_user.registration.confirmation.enabled');

        $process = $formHandler->process($confirmationEnabled);
        ...
```

services.yml
```
    acme_user.registration.form:
        class: Acme\UserBundle\Form\Type\RegistrationFormType
        arguments: ["%fos_user.model.user.class%", "@node.client"]
        tags:
            - { name: form.type, alias: acme_user_registration }

    acme_user.registration.form.handler:
        class: Acme\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@acme_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false
```

Result
```
Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Form\Handler\RegistrationFormHandler::__construct() must implement interface Symfony\Component\Form\FormInterface, instance of Acme\UserBundle\Form\Type\RegistrationFormType given,
```

Why?

**Comment by jayesbe** [comment]
I have die statements all over the place. I know for a fact its not even going into my custom RegistrationFormHandler.

**Comment by jayesbe** [comment]
Amazing.. I hope this helps someone

I had to change my services.yml from
```
    karmany_user.registration.form.handler:
        class: Karmany\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@acme_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false
```

to 
```
    karmany_user.registration.form.handler:
        class: Karmany\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false
```

Basically when defining your own custom form handler..  your argument for the form object **MUST** be the default form factory service "@fos_user.registration.form" and **NOT** your custom form. I suppose you may also define your own custom factory but I never tried.
