### ISSUE TITLE
Error translation

### ISSUE THREAD

**Issue by j3r3m067** [FriendsOfSymfony/FOSUserBundle#1877]
Your id for "Bad credential." is fault, you have forgotten the point (into the translation files)

**Comment by Ingannatore** [comment]
Could you please specify in which file(s) and line you have found that typo?

**Comment by j3r3m067** [comment]
FOSUserBundle.xx.yml line 15 (for example fr)

**Comment by Ingannatore** [comment]
I'm using the last version of FOSUserBundle and thet's what I see in the `fr` file (starting from line 14):

```yaml
# Security
security:
    login:
        username: "Nom d'utilisateur :"
        password: "Mot de passe :"
        remember_me: Se souvenir de moi
        submit: Connexion
```

Could you please specify the version of FOSUserBundle you are using?
