### ISSUE TITLE
Setting registration form name to null

### ISSUE THREAD

**Issue by seferov** [FriendsOfSymfony/FOSUserBundle#1900]
I want to set set form names without any parent (such as, fos_user_registration_form). So I changed configuration:

```
fos_user:
    registration:
        form:
            type: fango_user_registration
            name: null
```

which renders form fine with proper form names but submitting the registration form gives the following error:
> This form should not contain extra fields.
