### ISSUE TITLE
No mapping found for field 'roles'

### ISSUE THREAD

**Issue by rpostolov** [FriendsOfSymfony/FOSUserBundle#1904]
Hi everybody !

I have some problem using FOSUserBundle.

I am on symfony 2.7.1 and i installed fosuserbundle  "~2.0@dev"

I create bundle User and admin but when i try to go to edit admin or else i have this problem

```
No mapping found for field 'roles' on class 'Ip\UserBundle\Entity\User'.
```

Can someone help me cause i'm stuck on this bug a long time already.

I use Fos use on Entity User :

``` php
use FOS\UserBundle\Model\User as BaseUser;

use Doctrine\ORM\Mapping as ORM;

/**
 * User
 *
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="Ip\UserBundle\Entity\UserRepository")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"admin" = "Ip\AdminBundle\Entity\Admin", "customer" = "Ip\CustomerBundle\Entity\Customer"})
 * 
 * @ORM\HasLifecycleCallbacks() 
 */
abstract class User extends BaseUser
```

And Here is for Entity Admin : 

``` php
namespace Ip\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use PUGX\MultiUserBundle\Validator\Constraints\UniqueEntity;

use Ip\UserBundle\Entity\User as User;

/**
 * Admin
 *
 * @ORM\Table(name="admin")
 * @ORM\Entity(repositoryClass="Ip\AdminBundle\Entity\AdminRepository")
 * @UniqueEntity(fields = "username", targetClass = "Ip\UserBundle\Entity\User", message="fos_user.username.already_used")
 * @UniqueEntity(fields = "email", targetClass = "Ip\UserBundle\Entity\User", message="fos_user.email.already_used")
 */
class Admin extends User
```

Here is my configuration in config.yml

``` yaml
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                auto_mapping: true
                filters:
                    oneLocale:
                        class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                        enabled: true

#AdminGenerator
admingenerator_generator:
    generator_cache: global_cache.provider
    # choose  and enable at least one
    use_propel:           false
    use_doctrine_orm:     true
    use_doctrine_odm:     false
    overwrite_if_exists: false
    base_admin_template: AdmingeneratorGeneratorBundle::base_uncompressed.html.twig
    #dashboard_welcome_path: root vers le dashboard de l'admin
    #dashboard_route:     MyDashboard_path
    generator_cache: global_cache.provider
    login_route: fos_user_security_login
    logout_route: fos_user_security_logout
    twig:
        use_form_resources: true
        use_localized_date: false
        date_format: Y-m-d
        datetime_format: Y-m-d H:i:s
        localized_date_format: medium
        localized_datetime_format: medium
        number_format:
            decimal: 0
            decimal_point: .
            thousand_separator: ,
    templates_dirs: []
    stylesheets: []
    javascripts: []

# Fos Users    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Ip\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager

pugx_multi_user:
  users:
    admin:
        entity: 
          class: Ip\AdminBundle\Entity\Admin
#          factory: 
        registration:
          form: 
            type: Ip\AdminBundle\Form\Type\RegistrationAdminFormType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default]
          template: IpAdminBundle:Registration:admin.form.html.twig
        profile:
          form:
            type: Ip\AdminBundle\Form\Type\ProfileAdminFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default] 
    customer:
        entity: 
          class: Ip\CustomerBundle\Entity\Customer
        registration:
          form: 
            type: Ip\CustomerBundle\Form\Type\RegistrationCustomerFormType
          template: IpCustomerBundle:Registration:customer.form.html.twig
        profile:
          form: 
            type: Ip\CustomerBundle\Form\Type\ProfileCustomerFormType

admingenerator_user:
     login_template: AdmingeneratorGeneratorBundle::base_admin.html.twig
```

Thanks a lot for your help !
