### ISSUE TITLE
[Profile Edit] Validation is not working

### ISSUE THREAD

**Issue by Plopix** [FriendsOfSymfony/FOSUserBundle#1922]
Hi guys,

I'm experiencing a weird issue. I'm with FOSUserBundle last version (see below). Last version of Symfony 2. (2.7.3)
I'm using FOSUserBundle with MongoDB, everything's working fine except the form validation on the Profile Edit form.

I got a Duplication entry when I use an existing email but the validation is working on the Register form.
Do you have an idea, something to check?

For me, I have correctly extended the FOSUserBundle in my Bundle etc.. I read read and read the documentation before posting this issue.

Let me know.

Thanks

```
$ php ../composer.phar show -i friendsofsymfony/user-bundle
name     : friendsofsymfony/user-bundle
descrip. : Symfony FOSUserBundle
keywords : User management
versions : * dev-master, 2.0.x-dev
type     : symfony-bundle
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/FriendsOfSymfony/FOSUserBundle.git 336d9cd8ba0c5a462b3e70be144a7bef5377b219
dist     : [zip] https://api.github.com/repos/FriendsOfSymfony/FOSUserBundle/zipball/336d9cd8ba0c5a462b3e70be144a7bef5377b219 336d9cd8ba0c5a462b3e70be144a7bef5377b219
names    : friendsofsymfony/user-bundle

autoload
psr-4
FOS\UserBundle\ => .

requires
php >=5.3.2
symfony/form ~2.3
symfony/framework-bundle ~2.3
symfony/security-bundle ~2.3
symfony/twig-bundle ~2.3

requires (dev)
doctrine/doctrine-bundle ~1.3
swiftmailer/swiftmailer ~4.3|~5
symfony/validator ~2.3
symfony/yaml ~2.3
willdurand/propel-typehintable-behavior ~1.0

suggests
willdurand/propel-typehintable-behavior Needed when using the propel implementation
```

**Comment by stof** [comment]
Can you show your configuration for the bundle (and your overwritten profile form type if you have overwritten it) ?

**Comment by Plopix** [comment]
Thx @stof, sure!

I've also checked to add my own validation.yml. The result was that I had 2 same "correct" errors in Registration form but always nothing ( and the duplicate entry) in the Profile form.

Here is the config:
```yaml
fos_user:
    db_driver: mongodb
    firewall_name: ezpublish_front
    user_class: My\Bundle\UserBundle\Document\User
    service:
        user_manager: my.fos_user_manager
    profile:
        form:
            type: my_user_profile
    change_password:
        form:
            type: my_user_change_password
    registration:
        confirmation:
            enabled: true
        form:
            type: my_user_registration
```

Here is the services:
```yaml
    my.my_user_profile.form.type:
        class: My\Bundle\UserBundle\Form\Type\Profile
        arguments: [@my.userwrapped_to_user.data_transformer]
        tags:
            - { name: form.type, alias: my_user_profile}

    my.my_user_change_password.form.type:
        class: My\Bundle\UserBundle\Form\Type\ChangePassword
        arguments: [@my.userwrapped_to_user.data_transformer]
        tags:
            - { name: form.type, alias: my_user_change_password}

    my.my_user_registration.form.type:
        class: My\Bundle\UserBundle\Form\Type\Registration
        arguments: [@my.userwrapped_to_user.data_transformer]
        tags:
            - { name: form.type, alias: my_user_registration}
```

And about the form type,
```php
/**
 * Class Registration
 */
class Registration extends AbstractType
{
    /**
     * UserTransformer
     *
     * @var UserWrappedToUser
     */
    protected $userTransformer;

    /**
     * Constructor
     *
     * @param UserWrappedToUser $userTranformer
     */
    public function __construct( UserWrappedToUser $userTranformer )
    {
        $this->userTransformer = $userTranformer;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm( FormBuilderInterface $builder, array $options )
    {
        parent::buildForm( $builder, $options );
        $builder->add( 'firstname' );
        $builder->add( 'lastname' );
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'fos_user_registration';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'my_user_registration';
    }
}
```

```php
/**
 * Class Profile
 */
class Profile extends AbstractType
{
    /**
     * UserTransformer
     *
     * @var UserWrappedToUser
     */
    protected $userTransformer;

    /**
     * Constructor
     *
     * @param UserWrappedToUser $userTranformer
     */
    public function __construct( UserWrappedToUser $userTranformer )
    {
        $this->userTransformer = $userTranformer;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm( FormBuilderInterface $builder, array $options )
    {
        parent::buildForm( $builder, $options );
        $builder
            ->remove('current_password')
            ->remove('username')
            ->add(...)
            ->add(...)
            ->add(...)
            ->add(...)
            ->add(...)
            ->add(...)
            ->add(...);
        $builder->addViewTransformer( $this->userTransformer );
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'fos_user_profile';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'my_user_profile';
    }
}
```
