### ISSUE TITLE
With Symfony 2.7 - MongoDB

### ISSUE THREAD

**Issue by TKeePeR** [FriendsOfSymfony/FOSUserBundle#1941]
When having multiple connections to multiple mongodb's databases, login always returns 'User Disabled' error.

my config.yml ('default' is the database with User and UserGroup collections)
```yml
doctrine_mongodb:
    connections:
        default:
            server: %mongo_server%
            options: {}
        cache:
            server: %mongo_server_cache%
    default_database: %mongo_database%
    document_managers:
        default:
            auto_mapping: true
            database: %mongo_database%
        cache:
            auto_mapping: true
            database: %mongo_database_cache%
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: ThisIs\MyBundle\Document\User
    group:
        group_class: ThisIs\MyBundle\Document\UserGroup

```
