### ISSUE TITLE
MongoDB with multiple connections ; hydrate problem

### ISSUE THREAD

**Issue by beesofts** [FriendsOfSymfony/FOSUserBundle#1992]
I'm using many connections to use data from many mongoDB databases. I followed the steps from symfony page to configure FOSUB. 
When I configure more than 1 connection for doctrine_mongodb, mapping configuration from FOS\UserBundle\Model\User don't seems to be loaded. I am able to persist documents, but reading won't work. I can read the fields I set in my own User class, but all fields from FOSUB class (email for example) is set to null.
Here is the config from my config.yml file:

```
doctrine_mongodb:
    connections:
        default:
            server: mongodb://%mongo_host%:%mongo_port%
            options:
                username: %mongo_user%
                password: %mongo_password%
        worker00:
            server: mongodb://%mongo_host%:%mongo_port%
            options:
                username: %mongo_user%
                password: %mongo_password%
    default_database: sociallymap
    document_managers:
        default:
            auto_mapping: true
        worker00:
            auto_mapping: true

fos_user:
    db_driver: mongodb
    firewall_name: main
    model_manager_name: default
    user_class: AppBundle\Document\User
```

This configuration works fine for my others documents.

If necessary I can provide a full sample project.
