### ISSUE TITLE
Unrecognized options "0, 1, 2, 3" under "security.firewalls.access_control"

### ISSUE THREAD

**Issue by nkl90** [FriendsOfSymfony/FOSUserBundle#2009]
I completed all steps in this [manual](symfony.com/doc/current/bundles/FOSUserBundle/index.html). But when I try to execute:
> bin/console doctrine:schema:update --force

I get this exception:

> [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
> Unrecognized options "0, 1, 2, 3" under "security.firewalls.access_control"

**Comment by xabbuh** [comment]
How does your security configuration look like?

**Comment by nkl90** [comment]
This is my security.yml:
```
# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        #ROLE_CUSTOMER: ROLE_USER
        #ROLE_MERCHANT: ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true
            
        access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

```
