### ISSUE TITLE
Infinite redirect for /register & /profile pages after a fresh install

### ISSUE THREAD

**Issue by 3KyNoX** [FriendsOfSymfony/FOSUserBundle#2014]
Hello !

I just set-up FOSUser in my project, login page works great but register and profile page returns an infinite loop : 

> Chrome -> ERR_TOO_MANY_REDIRECTS

Here is my security config file : 

```yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
```

Any idea ?

Thanks !

**Comment by sunlix** [comment]
@3KyNoX Maybe your routes collide with any of your own defined routes?
Can you provide your routes?
Maybe there is a route with some parameters?

**Comment by 3KyNoX** [comment]
Not sure it comes from here, here is the routes (fosuser bundle part) :

```yml
# FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
```
