### ISSUE TITLE
Mongodb - class not found in configured namespaces

### ISSUE THREAD

**Issue by StefanGlaesser** [FriendsOfSymfony/FOSUserBundle#2075]
Hello,

I'm always getting a

```
 [Doctrine\Common\Persistence\Mapping\MappingException]
 The class 'AppBundle\Document\User' was not found in the chain configured namespaces
```

using a fresh install.

This is my current composer.json.

```
"require": {
        "php": ">=5.5.9",
    "symfony/symfony": "2.8.*",
    "doctrine/orm": "^2.5.4",
    "doctrine/doctrine-bundle": "~1.4",
    "symfony/swiftmailer-bundle": "~2.3",
    "symfony/monolog-bundle": "~2.4",
    "sensio/distribution-bundle": "~5.0",
    "sensio/framework-extra-bundle": "^3.0.2",
    "incenteev/composer-parameter-handler": "~2.0",
    "doctrine/mongodb-odm": "~1.0",
    "doctrine/mongodb-odm-bundle": "~3.0",
    "friendsofsymfony/user-bundle": "~2.0@dev"
},
```

And some parts of my config.yml

```
# Mongo-DB Configuration
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: portal
    document_managers:
        default:
            auto_mapping: true

# FOS-User Bundle
fos_user:
    db_driver: mongodb # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Document\User
```

I don't know what todo any more. What's wrong? What else can I do?
