### ISSUE TITLE
Unrecognized options "handler" under "fos_user.profile.form"

### ISSUE THREAD

**Issue by Azouz-Jribi** [FriendsOfSymfony/FOSUserBundle#2078]
Hello!
```
"friendsofsymfony/user-bundle": "2.0.x-dev#6ccff96 as 1.3"
"friendsofsymfony/oauth-server-bundle": "1.4.2",
"friendsofsymfony/rest-bundle": "^1.7",
```
AND
```
"sonata-project/user-bundle": "^2.2"
```
PHP 5.4 

```yaml
#config

fos_user:
    db_driver: orm
    firewall_name: api     
    user_class: Api\OauthUserBundle\Entity\User
    group:
        group_class:   Sonata\UserBundle\Entity\BaseGroup
    profile:
        # Authentication Form
        form:
            type:               fos_user_profile
            handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Authentication]
            user_manager: sonata.user.orm.user_manager
```
