### ISSUE TITLE
Stuck on step 7 of "Getting Started With FOSUserBundle"

### ISSUE THREAD

**Issue by mityukov** [FriendsOfSymfony/FOSUserBundle#2107]
Hi, I'm trying to do some very basic setup: installed the new fresh Symfony and tried to follow the guide at this URL: http://symfony.com/doc/master/bundles/FOSUserBundle/index.html

Either there's error in the guide or something else, but on Step #7 (Update your database schema) I get the following error message:
```
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "security.authentication.manager" has a dependency on a non-existent service "security.use
  r.provider.concrete.fos_userbundle".
```

Here's my **security.yml**:
```
# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_user_bundle:
            id: fos_user.user_provider.username
        # in_memory:
            # memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout: true
            anonymous: true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
```

Please advise what could that be as I can't even see where **security.authentication.manager** and **security.user.provider.concrete.fos_userbundle** come from…
