### ISSUE TITLE
How to override FOS\UserBundle\Model\User

### ISSUE THREAD

**Issue by JosuM** [FriendsOfSymfony/FOSUserBundle#2108]
Sorry @Einenlum, i understand now.

I explain my problem. I have a model that extends FOSUserBundle model.

When I set up the service, I get the configuration of the Model of my bundle but when I want to display that information in a view with getters, shows me the information of the FOSUserBundle getters.

My objective is to modify my custom Model and not having the need to touch the model of FOSUserBundle.

This is my code.

Thank you.
# app/config/config.yml

```
...
fos_user:
    db_driver: custom
    user_class: AppBundle\Model\User
    service:
        user_manager: user.web_service_manager
    firewall_name: main
```
# AppBundle/Model/User.php

```
namespace AppBundle\Model;

use FOS\UserBundle\Model\User as BaseUser;

class Usuario extends BaseUser {

    /**
     * @var integer
     *
     */
    protected $id;

    /**
     * @var string
     * 
     */
    protected $name;

    /**
     * @var string
     *
     */
    protected $lastname;

    function getId() {
        return $this->id;
    }

    function getName() {
        return $this->name;
    }

    function getLastName() {
        return $this->lastname;
    }

    function setId($id) {
        $this->id = $id;
    }

    function setName($name) {
        $this->name= $name;
    }

    function setLastname($lastname) {
        $this->lastname = $lastname;
    }
...
```
# app/config/security.yml

```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: user.web_service_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                login_path: fos_user_security_login 
                check_path: fos_user_security_check
            logout: 
                path: fos_user_security_logout
                target: index
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
```
# AppBundle/Resources/config/services.yml

```
services:
    user.web_service_manager:
        class: AppBundle\Model\WebServiceUserManager
        arguments: [ @security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, 'AppBundle\Model\User', @app.api]
```
