### ISSUE TITLE
Extending BaseGroup creates additional "fos_group" table

### ISSUE THREAD

**Issue by xDaizu** [FriendsOfSymfony/FOSUserBundle#2117]
I have this entity:

``` php

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_role_group")
 */
class RoleGroup extends BaseGroup
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $publicName;

}

```

which creates a `fos_role_group` table with the fields "id, name, roles, public_names" (those of my class, plus those of the extended class)... and also a `fos_group` table (id, name, roles) which is never used and doesn't actually cause any problems but I know it's there, I see it sitting there, useless, and it hurts the backside of my brain... is there any solution to this? Did I do something wrong?

PS: I don't know if it's related, but my `config.yml` looks like this:

``` yml

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Acme\UserBundle\Entity\FOSUser   
    group:
        group_class: Acme\UserBundle\Entity\RoleGroup
    resetting:
        token_ttl: 0
        form:
            type: Acme\UserBundle\Form\Type\ResettingFormType
```
