### ISSUE TITLE
Disconnected just after check_path

### ISSUE THREAD

**Issue by jbchateaux** [FriendsOfSymfony/FOSUserBundle#2144]
Hello Guyz,

I got a terrible issue while testing my app in production environment (everything is ok on local).
When I try to loggin (setup intercept_redirects to true), I'm correctly redirected to /login-check and the toolbar say that I am correctly logged. Then, whatever page I want to go I am no longer logged.

I don't know where the problem come from, do you have any ideas ?

Thanks

**Comment by stof** [comment]
Please post your SecurityBundle configuration (generally living in security.yml)

**Comment by jbchateaux** [comment]
````yml
    security:
        encoders:
            UserBundle\Entity\User: sha512

        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

        providers:
            main:
                id: fos_user.user_provider.username

        firewalls:
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
            main:
                pattern: ^/
                anonymous: true
                provider: main
                form_login:
                    login_path: /
                    check_path: fos_user_security_check
                    default_target_path: modules #dashboard/modules
                logout:
                    path:       fos_user_security_logout
                    target:     /


        access_control:
            - { path: ^/dashboard, roles: ROLE_USER }
            - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }

```
