### ISSUE TITLE
How to override FOSUserBundle ProfileFormType -- Symfony 3.1?

### ISSUE THREAD

**Issue by dwangus** [FriendsOfSymfony/FOSUserBundle#2147]
I've googled so many other options, and there are so many similar stack overflow questions that I've looked at, but they all dealt with outdated versions of Symfony or FOSUserBundle... It doesn't help that the FOSUserBundle documentation doesn't exactly cover how to add custom fields to the Profile page, only the registration page.

So how do I make custom fields I've added to the User class show up in the user's profile page? I've tried pretty much all other stack overflow attempts.

Here's my services.yml:

``` yaml
services:
    app.profile.form.type:
        class: AppBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }
```

Here's my config.yml:

``` yaml
fos_user:
    profile:
        form:
            type: AppBundle\Form\ProfileFormType
```

And just one iteration of many of my Profile class:

``` php
namespace AppBundle\Form\Type;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
class ProfileFormType extends AbstractType
{
    public function buildUserForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('pokemon');
    }

public function getParent() 
{
    return 'FOS\UserBundle\Form\Type\ProfileFormType';
}

public function getBlockPrefix()
{
    return 'app_user_profile';
}

// For Symfony 2.x
public function getName()
{
    return $this->getBlockPrefix();
}

}
```
