### ISSUE TITLE
Disable default validation group when resetting password

### ISSUE THREAD

**Issue by exchentrix** [FriendsOfSymfony/FOSUserBundle#2202]
Hey,

thank you for this awesome. I've overrided the registration form type:

```yaml
# fos user
fos_user:
    db_driver: propel
    firewall_name: site
    user_class: BusinessBundle\Model\Acl\Customer\Customer
    registration:
        form:
            type: BusinessBundle\Form\Type\RegistrationType
```

The validation config for my model:

```yaml
BusinessBundle\Model\Acl\Customer\Customer:
    properties:
        name:
            - NotBlank:
                message : messages.null
        email:
            - NotBlank:
                message : messages.null
            - Email:
                message : messages.invalid_email
            - SiteBundle\Validator\Constraints\EmailNotExists: ~
        plainPassword:
            - NotBlank:
                message : messages.null
```
The validator works as expected for registration.

Now, if I want to reset my password, I get an "messages.email_already_exists" form error. It seems, that the resetPasswordFormType is also using the default validation:

`validation_groups: [0 => ResetPassword, 1 => Default]`

Is it possible to disable this or is there something I'm doing wrong?

Best,
Christian
