### ISSUE TITLE
/login redirects to /profile

### ISSUE THREAD

**Issue by alister** [FriendsOfSymfony/FOSUserBundle#2245]
Following pull request #2236 when a currently-logged in user visits a FOSUser generated page (such as /login, /register, /resetting/request or /register) they will be redirected by default to `/profile` (the route named `fos_user_profile_show`).

To change the default route, add a new key in your Symfony configuration: `fos_user.user.default_route`. 

```yml
    fos_user:
        user:
            default_route: app.my.profile_page
```

This change also means that you can no longer just visit `/login` to login as someone else, but must explicitly logout first. This affected a functional test I had written.
