### ISSUE TITLE
Problem with ldap compare password with sf3

### ISSUE THREAD

**Issue by jfsenechal** [FriendsOfSymfony/FOSUserBundle#2251]
Hi,
I'm trying to configure ldap with fosuserbundle but I have an error : 
User Warning: Expected known_string to be a string, NULL given

[http://i.stack.imgur.com/y9gyh.png]

My config files :

**security.yml**

`providers:
    fos_userbundle:
        id: fos_user.user_provider.username

```
users_ldap:
    ldap:
        service: ldap
        base_dn: "OU=USERS,DC=domain,DC=be"
        search_dn: "CN=ps,OU=apps,DC=domain,DC=be"
        search_password: password
        default_roles: ROLE_USER
        uid_key: sAMAccountName
chain_provider:
    chain :
        providers: [users_ldap, fos_userbundle]
```

encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    AcSecurityBundle\Entity\User: sha512

firewalls:        

```
secured_area:
    pattern:    ^/
    anonymous: true
    provider: chain_provider
    form_login:
        csrf_token_generator: security.csrf.token_manager
        use_referer: true
    form_login_ldap:
        service: ldap
        use_referer: true
    logout: true`
```

**service.yml**

`services:
ldap:
    class: 'Symfony\Component\Ldap\LdapClient'
    arguments:
        - ldap.domain.be   # host
        - 636         # port
        - 3           # version
        - true       # SSL
        - false        # TLS`

What's wrong ?
Thanks
