### ISSUE TITLE
[Feature Request] Email / Username Blacklist

### ISSUE THREAD

**Issue by homersimpsons** [FriendsOfSymfony/FOSUserBundle#2431]
**Describe the feature**: Add an easy to implement blacklist for Email and/or username

In FOSUserBundle there could be params: `username.blacklist`, `email.blacklist` etc...
Those fill with array of Regexp and if a Regexp match then the registration won't be allowed.

I've found [this request](https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1450) then maybe I have to use validation contraint too instead of implement this.

**Comment by SebTM** [comment]
I think there is no need to add a specific feature for that as you are already able to achieve this by defining a own validation group and adding it to the configuration.

```
# app/config/config.yml
fos_user:
    # ...
    registration:
        form:
            type: AppBundle\Form\RegistrationType
            # if you are using Symfony < 2.8 you should use the type name instead
            # type: app_user_registration
            validation_groups:  ['Registration', 'Default', 'MyGroup']
```
The groups "Registration" and "Default" are from FOSUserBundle you can leave it if you like the "basic"-validation provided there or just handle the complete validation with your custom group.

In your custom-group you can use the [Regex-Constraint](http://symfony.com/doc/current/reference/constraints/Regex.html) to get the desired result.
