### ISSUE TITLE
LoginListener write into file after login

### ISSUE THREAD

**Issue by kironet** [FriendsOfSymfony/FOSUserBundle#2488]
How can I write log into file after user's login?

I have this:

```
<?php
namespace Web\AdminBundle\EventListener;

use FOS\UserBundle\Model\UserManagerInterface;
use Symfony\Component\Security\Http\Event\InteractiveLoginEvent;

class LoginListener {

    protected $userManager;

    public function __construct(UserManagerInterface $userManager){
        $this->userManager = $userManager;
    }

    public function onSecurityInteractiveLogin(InteractiveLoginEvent $event)
    {
        $user = $event->getAuthenticationToken()->getUser();
        $myfile = fopen("login.txt", "w");
        fwrite($myfile, 'some-text');
        fclose($myfile);
    }
}
```

then:

```
login_listener:
    class:  Web\AdminBundle\EventListener\LoginListener
    arguments:
        userManager: "@fos_user.user_manager"
    tags:
        - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
```

But this doesn't work, there is no error. I tried just call die('some-text') to make sure it's working, bot it did nothing.

Thank you
