### ISSUE TITLE
yaml configured FOSUserBundle fails @ schema update: "Class 'AppBundle\Entity\User' does not exist"

### ISSUE THREAD

**Issue by albion2** [FriendsOfSymfony/FOSUserBundle#2545]
I'm working on FOSUSerBundle installation & configuration, following the instructions @

```
    https://symfony.com/doc/master/bundles/FOSUserBundle/index.html.
```

I'm running

```
	composer info
		...
		friendsofsymfony/user-bundle         v2.0.0  Symfony FOSUserBundle
		...
		symfony/symfony                      v3.2.7  The Symfony PHP framework
		...
	php -v
		PHP 7.1.5-dev (cli) (built: Apr  7 2017 13:34:53) ( NTS )
```

I've decided to use the Symfony yaml, instead of the annotation, config format.  

I've followed the instructions verbatim; my files were simply copied-n-pasted from the instructions.

When I exec the 

```
	php bin/console doctrine:schema:update --force
```

command, it fails with:

```
	"[Doctrine\Common\Persistence\Mapping\MappingException]
	 Class 'AppBundle\Entity\User' does not exist"
```

What additional step/fix is needed to get the yaml-config's User class to be recognized?

**Comment by xabbuh** [comment]
Did you create the user class as described in https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-3-create-your-user-class?

**Comment by albion2** [comment]
Yes.  Following

```
	Step 3: Create your User class¶
	...
	a) Doctrine ORM User class¶

	If you're persisting your users via the Doctrine ORM, then your User class should live in the Entity namespace of your bundle and look like this to start:
	...

	YAML
		# src/AppBundle/Resources/config/doctrine/User.orm.yml
		AppBundle\Entity\User:
		    type:  entity
		    table: fos_user
		    id:
		        id:
		            type: integer
		            generator:
		                strategy: AUTO
```

my config is, exactly,

```
cat src/AppBundle/Resources/config/doctrine/User.orm.yml
# src/AppBundle/Resources/config/doctrine/User.orm.yml
AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
```

**Comment by xabbuh** [comment]
I am not talking about the config, but the PHP class itself. Where did you place it? What does it look like?

**Comment by albion2** [comment]
That's what I meant.  It's exactly what & where the instructions say to do

> **_your User class should_** live in the Entity namespace of your bundle and **_look like this to start:_**

```
# src/AppBundle/Resources/config/doctrine/User.orm.yml
AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
```
