### ISSUE TITLE
Not generating salt when using PlaintextPasswordEncoder

### ISSUE THREAD

**Issue by nenadalm** [FriendsOfSymfony/FOSUserBundle#2551]
**Symfony FOSUserBundle versions**: master

**Description of the problem including expected versus actual behavior**:
Problem is that if I want to use the PlaintextPasswordEncoder on dev, password+salt is concatenated and stored into db (but it has too long value for the column, so it crashes).

**Steps to reproduce**:
 1.
```yaml
security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: plaintext
```
 2. Try to reset password
 3. Exception is thrown (in case the password+salt doesn't fit the column length)

**Suggested fix**:
change ```else``` to ```elseif (!$encoder instanceof PlaintextPasswordEncoder)```
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/730a8a5f6633ae913a838d26b1c7156faa6ed697/Util/PasswordUpdater.php#L44
