### ISSUE TITLE
Allowing to get the Custom Form with its service name

### ISSUE THREAD

**Issue by pc-magas** [FriendsOfSymfony/FOSUserBundle#2556]
On my personal Symfony 3 project that uses that uses the FosUserBudnel v2.0.0 I created EditUserProfile one:

```
namespace AppUserBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use AppUserBundle\Form\Type\PurifiedTextAreaType;

class UserProfileFormType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		parent::buildForm($builder, $options);        
		$builder->add('name',TextType::class,array('label'=>'profile.first_name','required' => false));
		$builder->add('surname',TextType::class,array('label'=>'profile.surnname','required' => false));
		$builder->remove('username');
		$builder->add('username',TextType::class,['required' => false]);
		$builder->add('email',TextType::class,['required' => false]);
		$builder->add('description',TextareaType::class,['required' => false]);
		$builder->remove('current_password');
	}
	
	public function getParent()
	{
		return 'FOS\UserBundle\Form\Type\ProfileFormType';
	}
	
	public function getBlockPrefix()
	{
		return 'app_user_profile';
	}
		
	// For Symfony 2.x
	public function getName()
	{
		return $this->getBlockPrefix();
	}
}
```
And as Documentation says I created the following `services.yml`

```
app_user.user_profile_form:
    class: AppUserBundle\Form\Type\UserProfileFormType
    tags:
      - { name: form.type, alias: app_user_profile }
```

And I put the following configuration to my `config.yml`

```
fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: '%user_class%'
  from_email:
    address: "somemail@example.com"
    sender_name: "App Mailer"
  registration:
    confirmation:
      enabled: false
  profile:
    form:
      type: AppUserBundle\Form\Type\UserProfileFormType
```
 
The problem is that if I want to put a common Data transformer eg. HTMLPurifierTransformer I have a VERY big problem because I cannot declare some sort of service and the FormBuilder uses default parameters for constructing the Form.

So I think it would be great if I just could also set the following on my `config.yml`

```
fos_user:
 ....
  profile:
    form:
      type: 'app_user.user_profile_form'
```

Or even a custom FormFactory Class.
