### ISSUE TITLE
Groups not working / "Class "FlowFusion\UserBundle\Entity\Group" sub class of "FOS\UserBundle\Model\Group" is not a valid entity or mapped super class."

### ISSUE THREAD

**Issue by antond1990** [FriendsOfSymfony/FOSUserBundle#2574]
**Symfony FOSUserBundle versions**: 2.0.1

**Description of the problem including expected versus actual behavior**: I want to add user groups to the FlowFusion/UserBundle. By following your docs for "2.0" of the FOSUserbundle, I got the error message in the subject of this issue.
You can see the current code of the bundle here: https://github.com/flowfusion/user-bundle/tree/dev

**My FOSUserBundle-config**:
```
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: FlowFusion\UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    group:
        group_class: FlowFusion\UserBundle\Entity\Group
```

Thanks for your help.
