### ISSUE TITLE
Memcached LOGIN SF 3.3

### ISSUE THREAD

**Issue by AntoineTesson** [FriendsOfSymfony/FOSUserBundle#2593]
fosuser : 2.0.1

Hi,

when i log on my app with fosuser no problem when session are cached in files (native) or on PDOSession  with the handler_id

But when i use memcached, i need always to log two times ! for to be connected, i cant understand this problem

(the first time, no error, no result, no return, its like a refresh as F5) and the second time its ok. 

   ```
 session: 
        #name: SESSID
        handler_id: session.handler.memcached
        cookie_lifetime: 86400
        #gc_maxlifetime: 1440
        #gc_divisor: 1000
        #gc_probability: 1
        #save_path: ~

    session.memcached:
        class: Skies\AdminBundle\Utils\MemcachedWrapper
        arguments:
            #persistent_id: '%memcached_prefix%'
        calls:
            - [ addServer, [ '%memcached_host%', '%memcached_port%' ] ]
            
    session.handler.memcached:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: [ "@session.memcached", { prefix: '%memcached_prefix%', expiretime: '%memcached_expire%' } ]       
```
