### ISSUE TITLE
The service "fos_user.mailer" has a dependency on a non-existent service "mailer"

### ISSUE THREAD

**Issue by RobertRajcool** [FriendsOfSymfony/FOSUserBundle#2600]
```
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: 'mail.redington.co.in'
        sender_name: 'cloudsupport'
```

**Comment by broiniac** [comment]
Hi there! What version of Symfony and FOSUserBundle are you using?

On freshly installed SF3.3 with Flex i had to set:
```yaml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: '%env(MAILER_USER_ADDRESS)%'
        sender_name: '%env(MAILER_USER_NAME)%'
    service:
        mailer: 'fos_user.mailer.noop'
        # mailer: 'fos_user.mailer.twig_swift' # Works as well
```
to quite this error. It didn't however remove the problem.

Does your SwiftmailerBundle is properly configured?
