### ISSUE TITLE
How to redirect to a specific URL after login?

### ISSUE THREAD

**Issue by Bacteries** [FriendsOfSymfony/FOSUserBundle#262]
Hi,
I'm using UserBundle that fit well my need, so thanks!

I would like to rediect my user to a specific mage when he logins, but I don't find where do to this, I seek in firewalls configuration but found nothing.

Thanks for your help.

Eric

**Comment by todstoychev** [comment]
Just add in security.yml:
```yml
security:
...
    firewalls:
            main:
                form_login:
                    default_target_path: /where/you/want/to/redirect/after/login
...
```

**Comment by thomasFoglia** [comment]
In security.yml :

```
...
firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: offer_index
                always_use_default_target_path: true
...
```
