### ISSUE TITLE
Use two diffrent SMTP with FOSUserBundle 

### ISSUE THREAD

**Issue by sbeline** [FriendsOfSymfony/FOSUserBundle#2648]
Hi !
I use , one of my website to power on my other website. The point is when i use FOSUserBundle,
I need to configure the yml to have a second mailer form

i have this:
```yaml
services:
   project.mailer.twig_swift:
         class: AppUserBundle\Mailer\TwigSwiftMailer
fos_user:
    db_driver: orm
    service:
      mailer: wmc.common.fos.twig_helper_mailer
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
      address: %send_mails_from%
      sender_name: %send_mails_from_name%
    group:
        group_class: AppBundle\Entity\Group
    registration:
        form:
            type: registration_form
        confirmation:
            enabled:    true # change to true for required email confirmation
            template:   AppUserBundle:Default:Registration/email.txt.twig
```

but i want some thing more like this:
```yaml
services:
   project.mailer.twig_swift:
         class: AppUserBundle\Mailer\TwigSwiftMailer
fos_user:
    db_driver: orm
    service:
      mailer: wmc.common.fos.twig_helper_mailer
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
      address: %send_mails_from%
      sender_name: %send_mails_from_name%
    from_email2:
      address: %send_mails_from_scd%
      sender_name: %send_mails_from_name_scd%
    group:
        group_class: AppBundle\Entity\Group
    registration:
        form:
            type: registration_form
        confirmation:
            enabled:    true # change to true for required email confirmation
            template:   AppUserBundle:Default:Registration/email.txt.twig
```

Or maybe, i have to do something more like this https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1035 ??? 

Or get the FOS\UserBundle\Mailer\Mailer\TwigSwiftMailer and redefine the method 
```php
protected function sendMessage($templateName, $context, $fromEmail, $toEmail)
```

**Comment by sbeline** [comment]
i finally decided to use the FOS\UserBundle\Mailer\Mailer\TwigSwiftMailer.

i move my fos_user.yml like this : 
```yaml
    project.mailer.twig_swift:
         class: AppUserBundle\Mailer\TwigSwiftMailer

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
      address: %send_mails_from%
      sender_name: %send_mails_from_name%
    group:
        group_class: AppBundle\Entity\Group
    registration:
        form:
            type: registration_form
        confirmation:
            enabled:    true # change to true for required email confirmation
            template:   AppUserBundle:Default:Registration/email.txt.twig
    service:
        mailer: project.mailer.twig_swift
```

i create a service.yml for the twig mailer 
```yaml
//AppUserBundle\Ressources\config\service.yml
services:
    project.mailer.twig_swift:
      class: AppUserBundle\Mailer\TwigSwiftMailer
      public: false
      arguments:
          - '@mailer'
          - '@router'
          - '@twig'
```
and the TwigSwiftMailer:
```php
<?php
////AppUserBundle/Mailer/TwigSwiftMailer.php
namespace AppUserBundle\Mailer;

use FOS\UserBundle\Model\UserInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use FOS\UserBundle\Mailer\TwigSwiftMailer as BaseSwiftMailer;

class TwigSwiftMailer extends BaseSwiftMailer
{
      protected $mailer;
      protected $router;
      protected $twig;


      public function __construct(\Swift_Mailer $mailer, UrlGeneratorInterface $router, \Twig_Environment $twig)
      {
          $this->mailer = $mailer;
          $this->router = $router;
          $this->twig = $twig;
      }


      public function sendNewEmailMessage(UserInterface $sender,UserInterface $receiver)
      {

          $url = $this->router->generate('homepage');
          $context = array(
              'user' => $user,
              'homepageUrl' => $url
          );

          $this->sendMessage($template, $context, $sender->getEmail(), $receiver->getEmail());
      }
}
```

and now when i regestier an user user i have the following issues: 
```error
2017-11-27 14:57:48] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Too few arguments to function AppUserBundle\Mailer\TwigSwiftMailer::__construct(), 0 passed in /var/www/vhosts/appwapp.com/bidsettle.appwapp.com/app/cache/prod/appProdProjectContainer.php on line 3496 and exactly 3 expected" at /var/www/vhosts/appwapp.com/bidsettle.appwapp.com/src/AppUserBundle/Mailer/TwigSwiftMailer.php line 18 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Too few arguments to function AppUserBundle\\Mailer\\TwigSwiftMailer::__construct(), 0 passed in /var/www/vhosts/appwapp.com/bidsettle.appwapp.com/app/cache/prod/appProdProjectContainer.php on line 3496 and exactly 3 expected at /var/www/vhosts/appwapp.com/bidsettle.appwapp.com/src/AppUserBundle/Mailer/TwigSwiftMailer.php:18)"} []
```

the point is my definition of the service twig don't passed the diffrent argument to my class twigmailer and i don't know why ?

**Comment by stof** [comment]
Well, in your snippet above, you show 2 different definitions of the services:

```yaml
services:
   project.mailer.twig_swift:
         class: AppUserBundle\Mailer\TwigSwiftMailer
```

is in fos_user.yml, and this service definition is incomplete.

Depending on the order of imports, this file might be loaded after `service.yml` and so win over it

**Comment by sbeline** [comment]
Thank you you i just change the fos_user.yml : 
```yml
    project.mailer.twig_swift:
         class: AppUserBundle\Mailer\TwigSwiftMailer
          arguments: ['@mailer', '@router','@twig']

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
      address: %send_mails_from%
      sender_name: %send_mails_from_name%
    group:
        group_class: AppBundle\Entity\Group
    registration:
        form:
            type: registration_form
        confirmation:
            enabled:    true # change to true for required email confirmation
            template:   AppUserBundle:Default:Registration/email.txt.twig
    service:
        mailer: project.mailer.twig_swift
```
and delete the service definition , thank a lot have a good day !

**Comment by sbeline** [comment]
After this post i will close this issus, so i finally configure 2 smtp.
for this i use: 
\\fos_user.yml
```yml
services:
    project.mailer.twig_swift:
         class: AppUserBundle\Mailer\TwigSwiftMailer
         arguments:
            -
              mailers: # the two swift mailer 
                  mailer1: '@mailer'
                  mailer2: '@swiftmailer.mailer.mailer2'
              translator:
                  local: '@translator' #my_local_var
              email:
                  add_pv_fr: %send_mails_from_fr_PV%
                  add_fr: %send_mails_from_fr_CA%
                  add_en: %send_mails_from_en_CA%
                  sender_bs: %send_mails_from_name%
                  sender_pv: %mailer2_username%
            - '@router'
            - '@twig'
            -
              template: #all my email template for difrent website
                  confirmation: '%fos_user.registration.confirmation.template%'
                  resetting: '%fos_user.resetting.email.template%'
                  pv_confirmation_template: 'AppUserBundle:Hosts:coco-bongo/Registration/email.txt.twig'
                  pv_resetting_template: 'AppUserBundle:Hosts:cocobongo.com/Resetting/email.txt.twig'
              from_email:
                  confirmation: '%fos_user.registration.confirmation.from_email%'
                  resetting: '%fos_user.resetting.email.from_email%'

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
      address: %send_mails_from_fr_PV%
      sender_name: %send_mails_from_name%
    group:
        group_class: AppBundle\Entity\Group
    registration:
        form:
            type: registration_form
        confirmation:
            enabled:    true # change to true for required email confirmation
            template:   AppUserBundle:Default:Registration/email.txt.twig
    service:
        mailer: project.mailer.twig_swift

```

after that i just use to modif my twigswiftmail.
Thanx for your response.
