### ISSUE TITLE
ProfileController is not available if registration.confirmation is not enabled

### ISSUE THREAD

**Issue by covex-nn** [FriendsOfSymfony/FOSUserBundle#2667]
If registration confirmation is not enabled, then `FOS\UserBundle\Controller\ProfileController` is not available, because `Resources/config/email_confirmation.xml` was not loaded and `fos_user.email_update_confirmation` service was not created.

> The service "fos_user.profiler.controller" has a dependency on a non-existent service "fos_user.email_update_confirmation".

I could temporary fix this error with configuration:

```yaml
fos_user:
    registration:
        confirmation:
            enabled: true
```

May be `confirmEmailUpdateAction` method should be moved out from `FOS\UserBundle\Controller\ProfileController` to a new controller?
