### ISSUE TITLE
Different User Classes per Firewall 

### ISSUE THREAD

**Issue by phiamo** [FriendsOfSymfony/FOSUserBundle#267]
Hi, 
i have an perhabs simple perhabs difficult issue:

I would like to have 2 different User Classes:

One FrontendUser and one BackendUser
because they have different Relations.

Now i think cause they are not allowed to loging in the other context, i use two firewalls.

But for both i would like to  have now fos_userbundle as user provider, giving me back the corresponding user.
But since i have to configure the user_class ans firewall for the whole fos bundle, it doesnt work.

Is there a common way to get around that?

We were thinking of creating a new child bundle which overrides the DependencyInjection Directory and creates a new config entry like 

``` yaml
backend_fos_user:
    db_driver: orm
    firewall_name: backend
    user_class: My\BackendBundle\Entity\BackendUser
```

so is this the right way?
i dont think so :(

but is there another one?

cheers
phil
