### ISSUE TITLE
Authentication request could not be processed due to a system problem.

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSUserBundle#2682]
**Symfony FOSUserBundle versions**: v2.0.2
**Symfony version**: 3.4
**Symfony Flex**: yes

**Description of the problem including expected versus actual behavior**:
Users cannot login when using correct credentials. The login form will give following error: "Authentication request could not be processed due to a system problem.". Cannot find any errors in the command prompt of the server. Also the log files are empty. 

**Steps to reproduce**:
 1. Install Symfony 3.4 with Symfony Flex
 2. Configure FosUserBundle like the config from 3.3
 3. Try to login

The config/packages/fos_user.yaml file looks like:
```
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: App\Entity\User
    from_email: # Use this node only if you don't want the global email address for the confirmation email
                address:        webmaster@example.com
                sender_name:    Webmaster JimmyD
    
    registration:
        confirmation:
            from_email: # Use this node only if you don't want the global email address for the confirmation email
                address:        webmaster@example.com
                sender_name:    Webmaster 
            enabled:    true # change to true for required email confirmation
            template:   FOSUserBundle:Registration:email.txt.twig
```
The config/routes.yaml looks like:
```
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
```
And the config/packages/security.yaml looks like:
```
security:
    providers:
        in_memory: { memory: ~ }
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            # activate different ways to authenticate
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                always_use_default_target_path: true
                default_target_path: /user/home
            logout:
                path: /logout
                target: /login

            anonymous:    true

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:     [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/profile/, role: ROLE_USER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
```
