### ISSUE TITLE
Too few arguments / Override RegistrationController

### ISSUE THREAD

**Issue by andevit** [FriendsOfSymfony/FOSUserBundle#2695]
Hi guys!
I'm a new symfony user.
Today I updated symfony to version 3.4.
I had already installed friendsofsymfony/user-bundle "~2.0@dev".

When I go on the registration page ( http://xxxxxx/app_dev.php/register/ ) I get this message:

Type error: Too few arguments to function FOS\UserBundle\Controller\RegistrationController::__construct(), 0 passed in /var/www/beta.jostratennis.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 195 and exactly 4 expected

`friendsofsymfony/user-bundle dev-master 5884948`

Where can I find the solution?

**Comment by grimmlink** [comment]
Same with profile with symfony 3.3

> Type error: Too few arguments to function FOS\UserBundle\Controller\ProfileController::__construct(), 0 passed in /data/www/dev/unilogin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 195 and exactly 3 expected

I guess it has something to do with autowiring

**Comment by r-ichard** [comment]
Same with here ! Symfony 3.3

`Type error: Too few arguments to function FOS\UserBundle\Controller\RegistrationController::__construct(), 0 passed in .../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 195 and exactly 4 expected`

**Comment by andevit** [comment]
For the moment i solved the problem with the overriding of the constructor:

```
class RegistrationController extends \FOS\UserBundle\Controller\RegistrationController
{
    public function __construct()
    {
    }
    public function registerAction(Request $request)
    {
....
```
This works for me.

**Comment by Tomsgu** [comment]
Controller overriding is **not** something that is related to fos user bundle. There is not even documentation section about it in a 2.0 version. You can [use events](https://symfony.com/doc/master/bundles/FOSUserBundle/controller_events.html). Or if you want to override controllers you should go to the [symfony documentation](https://symfony.com/doc/current/bundles/override.html#controllers) where you can find all information (note that controller is defined as a service). Or third solution is to create your own controller.

It is also not recommended to not use `dev` version. Especially if you still run 3.x symfony version.

**Comment by grimmlink** [comment]
it was in the 2.0 doc until 5 days ago...

https://github.com/FriendsOfSymfony/FOSUserBundle/commit/1c38ec1338883ca598020643e7a021b88be0d9e0

**Comment by Tomsgu** [comment]
Ah ok my bad. They probably decided to remove, because it has nothing to do with this bundle. And maintenance was quite hard. Especially after publishing recent symfony versions.

**Comment by grimmlink** [comment]
The problem is not directly with overriding of controllers (which is not best practice but sometimes you don't really have a choice and there is no reason it shouldn't work). I believe it has to do with autowiring configuration, but I didn't have time to look properly into it.

**Comment by Tomsgu** [comment]
The problem **is** with overriding. As I already mentioned [here](https://symfony.com/doc/current/bundles/override.html#controllers) is the section how to override any service. As you mentioned it tries to auto-wire your controller, but doesn't know how. That's why you have to create a compiler pass.

**Comment by Tomsgu** [comment]
To complete my answer. You should modify `fos_user.registration.controller` service definition.
```php
class Kernel extends BaseKernel implements CompilerPassInterface
{
  #....
  public function process(ContainerBuilder $container)
    {
        $definition = $container->findDefinition('fos_user.registration.controller');
        $definition->setClass(App\Entity\Overrides\RegistrationController::class);
    }
}
```

And change the default service definition by excluding RegistrationController.

```yaml
# default service configuration
services:
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Controller/Overrides}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        exclude: '../src/Controller/Overrides'
```
Auto-wiring doesn't seems to recognize that this service was overridden. (so you are probably right that it comes from there) I am not sure if this is an expected behavior, but for sure it has nothing to do with fos user bundle.

**Comment by doctoome** [comment]
Same problem

**Comment by sarpdorukaslan** [comment]
hi all,
bundle version is must be :
        "friendsofsymfony/user-bundle": "~2.0",
i change version my problem is solved.  

> I had already installed friendsofsymfony/user-bundle "~2.0@dev".I

**Comment by doctoome** [comment]
I solved this by andevit solution, and adding a route before fos ones

**Comment by xorik** [comment]
I found same issue and I didn't extend the controller. @sarpdorukaslan's fix helped me (I used ~2.0@dev)

**Comment by Aerendir** [comment]
I'm just experiencing the same exact issue after a `composer update` done yesterday.

The complete error is this:

Type error: Too few arguments to function FOS\UserBundle\Controller\ProfileController::__construct(), 0 passed in /Users/Aerendir/Documents/JooServer/_Projects/Coommercio/Apps/app-trust-back-me-www/var/cache/dev/jms_diextra/controller_injectors/SerendipityHQBundleUserBundleControllerProfileController.php on line 13 and exactly 3 expected

The new commit that causes the error is ef20dc8e86aa87b76353bfb32a607684134d65c6 (release 2.1.1). Previously working release was (2.0.2, commit 2fc8a023d7ab482321cf7ec810ed49eab40eb50f).

The complete error refers to JMSDIExtraBundle: this bundle caused issues with autowiring some time ago (see https://github.com/symfony/symfony/issues/23200 and https://github.com/symfony/symfony/issues/25695).

I'm going to check the changes between the two commits and test the manual calling of `setContainer`.

**Comment by Aerendir** [comment]
Ok, I'm going closer to solve the problem (@andevit solution is not a solution as it simply don't pass dependencies that maybe required).

In my `app/config/services.yml` file I've manually set the autowiring of my custom controllers:

```yaml
MyNamespace\Bundle\UserBundle\Controller\:
        resource: '../../src/MyNamespace/Bundle/UserBundle/Controller'
        autowire: true
```

The error that now comes out is:

> Cannot autowire service "SerendipityHQ\Bundle\UserBundle\Controller\ChangePasswordController": argument "$formFactory" of method "FOS\UserBundle\Controller\ChangePasswordController::__construct()" references interface "FOS\UserBundle\Form\Factory\FactoryInterface" but no such service exists. You should maybe alias this interface to one of these existing services: "fos_user.profile.form.factory", "fos_user.registration.form.factory", "fos_user.change_password.form.factory", "fos_user.resetting.form.factory". Did you create a class that implements this interface?

As clearly stated by the error, this is caused by the fact that all controllers implement the interface `FOS\UserBundle\Form\Factory\FactoryInterface` and this interface is implemented by 4 different concrete classes.

The real problem is that they are aliased and this causes the error because the autowire cannot recognize which dependency set in which controller.

To solve the problem in `app/config/services.yml` manually bind each service for each overridden controller:

```yaml
MyNamespace\Bundle\UserBundle\Controller\ChangePasswordController:
        bind:
            $formFactory: "@fos_user.change_password.form.factory"
```

**So, the complete configuration to solve the problem is this:**

```yaml
MyNamespace\Bundle\UserBundle\Controller\:
        resource: '../../src/MyNamespace/Bundle/UserBundle/Controller'
        autowire: true
MyNamespace\Bundle\UserBundle\Controller\ChangePasswordController:
        bind:
            $formFactory: "@fos_user.change_password.form.factory"
```

**Comment by imen-developer** [comment]
https://github.com/PUGX/PUGXMultiUserBundle/issues/156

**Comment by XWB** [comment]
Have a look at https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2744#issuecomment-369042634

**Comment by chiqui3d** [comment]
@Tomsgu your compiler pass example solved my problem in the update in version 4, but now when I want to add a global twig variable as usual in the overwritten controller, I can not.
I've tried to add an agurment like this:

`$definition->setArguments(array(new Reference('twig')));` 

But it doesn't work either. You know exactly how to do it?

**Comment by Moccine** [comment]
Symfony 4.3 ==> For me ProfileController overrider I add the empty construct and it works
```
use FOS\UserBundle\Controller\ProfileController as BaseController;

class ProfileController extends BaseController
{
    use ControllerTrait;
    public function __construct()
    {
    }
```

**Comment by doker42** [comment]
what is the ControllerTrait ?  what package?

**Comment by max4ever** [comment]
For a `resetController` you could copy from `vendor/friendsofsymfony/user-bundle/Resources/config/resetting.xml` the `fos_user.resetting.controller` section and have something like this in your `app/config/services/services.yml`: 

```
AppBundle\Controller\ResettingController:
    autowire: true
    arguments: 
      $eventDispatcher: '@event_dispatcher'
      $formFactory: '@fos_user.resetting.form.factory'
      $userManager: '@fos_user.user_manager'
      $tokenGenerator: '@fos_user.util.token_generator'
      $mailer: '@fos_user.mailer'
      $retryTtl: '%fos_user.resetting.retry_ttl%'
```

This "break" was introduced in 2.1.0

**Comment by WebDaMa** [comment]
SF 3.4
If you have autowire true and autoconfigure true in default this was enough for overriding the ResettingController:
`app/config/services.yml`

```
AppBundle\Controller\ResettingController:
    arguments:
      $formFactory: '@fos_user.registration.form.factory'
      $mailer: '@fos_user.mailer'
      $retryTtl: '%fos_user.resetting.retry_ttl%'
```
You also need this as standard:

```
  AppBundle\Controller\:
    resource: '../../src/AppBundle/Controller'
    public: true
    tags: [ 'controller.service_arguments' ]
```

**Comment by jmediatechnology** [comment]
Symfony 3.4: 

My `service.yml` looked like this: 

```
    super_awesome_controller:
        class: MyBundle\Controller\AwesomeDir\SuperAwesomeController
        arguments:
            - '@security.helper'
            - '@my.awesome.service'
```
            
            
I changed those lines to: 


```
    MyBundle\Controller\AwesomeDir\SuperAwesomeController:
        class: MyBundle\Controller\AwesomeDir\SuperAwesomeController
        arguments:
            - '@security.helper'
            - '@my.awesome.service'
```

And the error: `0 passed in /data/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 200 and exactly 2 expected`. disappeared.
