### ISSUE TITLE
Register the bundle in the contrib recipes repositories

### ISSUE THREAD

**Issue by glickel** [FriendsOfSymfony/FOSUserBundle#2704]
Hello,
Have you planed to register the bundle in the contrib recipes repositories to install this with flex ?
There is already a pull request for that [(here)](https://github.com/symfony/recipes-contrib/pull/210) but it's not finished and there is no update since 16 days. 

I had already add this bundle in a project with Symfony 4, and it's work well, so I can do a new pull request on the recipes-contrib repositories to register the bundle and a pull request in this bundle to update the documentation.

**Comment by Tomsgu** [comment]
I think it's still in progress. See this PR https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2707 from today.

**Comment by Tomsgu** [comment]
@covex-nn thanks for clarifying it. I don't know why I thought that https://github.com/symfony/recipes-contrib/pull/210 was created by you. That's why I thought that is in progress with your recent pull requests.

Anyway it's nice to hear that it's moving forward. 

About the `db_driver`: Is an acceptable solution to make it optional and set `fos_user.doctrine_registry` according to what we have in container? Or is there any other better way e.g. in recipe itself (don't know what is really possible to do there)?

**Comment by covex-nn** [comment]
@Tomsgu my solution is "use new default value for `db_driver`", a new "db_driver" will report about problems with configuration in runtime, without `doctrine-bundle` and etc.

See https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2708

**Comment by Tomsgu** [comment]
@covex-nn I like your idea :+1: (with no hidden behavior). So than we should wait for PR revisions and the session/security fix. 

Is there still something that can be done before a stable release?

**Comment by covex-nn** [comment]
@Tomsgu we could create recipe right here! I've created a new branch in my FOSUserBundle fork and merged boths PRs into it. To start using it and test it you could complete the following steps:

1. Execute `composer create-project symfony/skeleton .` inside empty directory

2. Create file `config/packages/fos_user.yaml` with the following content:

    ```yaml
    fos_user:
        firewall_name: main
        user_class: App\Entity\User
        from_email:
            address: "%env(MAILER_FROM_ADDRESS)%"
            sender_name: "%env(MAILER_FROM_NAME)%"
        registration:
            confirmation:
                enabled: false
        resetting: false
        service:
            mailer: fos_user.mailer.twig_swift
    ```

3. Create file `config/routes/fos_user.yaml` with the following content:

    ```yaml
    fos_user:
        resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    ```

4. Add `repositories` section to `composer.json`

    ```yaml
        "repositories": [
            { "type": "vcs", "url": "https://github.com/covex-nn/FOSUserBundle" }
        ],
    ```

5. Add `"friendsofsymfony/user-bundle": "recipe-dev as 2.1.0.1"` to `require` section of `composer.json`

6. Execute `composer update`

7. Execute `php -S 127.0.0.1:8000 -t public` and visit http://127.0.0.1:8000/register/

At this point we have installed, but not configured FOSUserBundle with "strange" behavior. We should help end-user to configure `db_driver`, `security` and (?) with `post-install.txt`, links, `manifest.json`, etc. But here my imagination ends, and even google translate cannot help me with it =)
