### ISSUE TITLE
/login path giving 404 in the production environment

### ISSUE THREAD

**Issue by emr** [FriendsOfSymfony/FOSUserBundle#2715]
**Symfony FOSUserBundle versions**:
* symfony **4.0.3**
* FosUserBundle **master**

**routes/fos_user.yaml**
```yaml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    options: { i18n: false }
```

no problem when I try to access `/login` path in the development environment.
but in the production environment, symfony giving 404 error.
