### ISSUE TITLE
Invalid token on form login

### ISSUE THREAD

**Issue by Quovandius** [FriendsOfSymfony/FOSUserBundle#2736]
Hi,

I have readed last topics on this subject, but i can't fix this problem.

I have worked with my current version 2.1.0 on development enrvironnment, no problem. 
Its on windows OS, with a wamp server, php5.6.

When i try to update on production server, based on Debian 8, with nginx php fpm, I have this problem of invalid token. (with current version or newest version of bundle)

I have try to : 
- set new permission on folder "var/", 
- set acl on folder, 
- check my configuration file, security file, 

I didn't find any solution.

I try to post a new issue because, on my last test, with settings :
- files dont changed
- same environnment (Debian 8 / nginx / php fpm 5.6)

I have try the dev-master version, 2.1.0 version => i have this bug
I have rollback on 2.0.1 version => no problem

At this moment, i have block any update on this bundle :/

Thanks for your help and your patience.

**Comment by jsnq** [comment]
Same issue for me with php7.1-fpm and Debian 8
The temporary solution is downgrade friendsofsymfony/user-bundle to v2.0.2

**Comment by johnstyle** [comment]
Same issue for me with php7.1-fpm and Debian 8
The temporary solution is downgrade friendsofsymfony/user-bundle to v2.0.2

**Comment by stof** [comment]
Can you give more details about the error you are getting ?

**Comment by Quovandius** [comment]
i have received the notification : token CSRF is invalid

i don't know how can i give you more details ? if you explain me i can provide more capture or information. Sorry.

**Comment by tattali** [comment]
Hi you need to add the following configuration to `config/packages/framework.yaml`:

```yml
framework:
    # ...
    csrf_protection: { enabled: true }
    templating:
        engines: ['twig']
```

And with symfony 4 you don't need to set permissions of `var/cache` or `var/log` folder 
Check the current documentation :
https://symfony.com/doc/current/setup/file_permissions.html

**Comment by Quovandius** [comment]
Hi,

The problem persist : 
- FosUserBundle v2.0.1 => this works, no change
- FosUserBundle v2.1.1 => don't works, no change

I give you my log : 

> [2018-02-21 10:57:44] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\InvalidCsrfTokenException(code: 0): Invalid CSRF token. at /home/user/projects/app.com/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php:76)"} []

**Comment by johnstyle** [comment]
With v2.1.1 of the bundle, the hidden field `_csrf_token` is not injected to the login form. 
I think the problem comes from there.

My Synfony version is 3.3.16

**Comment by stof** [comment]
well, are you overriding the controller or the route definition in your project ?

**Comment by Quovandius** [comment]
I have overriding controller as  : 
```
class SecurityController extends FosController
{
    public function renderLogin(array $data)
    {
        $requestAttributes = $this->container->get('request_stack')->getCurrentRequest()->attributes;

        if ('admin_login' === $requestAttributes->get('_route')) {
            $template = sprintf('UserBundle:Security:login_admin.html.twig');
        } else {
            $template = sprintf('UserBundle:Security:login.html.twig');
        }

        return $this->container->get('templating')->renderResponse($template, $data);
    }
}
```
I have overriding routing like this : 
```
admin_login:
    path:  /{_locale}/back-office/login
    requirements:
        _locale: "%locales_authorized%"
    defaults:
        _controller: FOSUserBundle:Security:login
        _locale: "%locale%"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}
    requirements:
        _locale: "%locales_authorized%"
    defaults:
        _locale: "%locale%"
```

I have overriding forms, do you need this code ?
