### ISSUE TITLE
Password resetting > request redirects to login

### ISSUE THREAD

**Issue by antondachauer** [FriendsOfSymfony/FOSUserBundle#2775]
config.yml
```
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Portal\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: true
        form:
            type: Portal\UserBundle\Form\RegistrationType
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
```

When I click on the password reset button, I am forwarded to the login. Button's Route:
```
<a href="{{ path('fos_user_resetting_request') }}" class="__input __button">{{ 'resetting.reset.submit'|trans }}</a>
```

It looks like a bug - I have no special configuration, only this. FOSUserBundle version is v2.1.2.
