### ISSUE TITLE
The "fos_user.registration.form.type" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You 

### ISSUE THREAD

**Issue by yurtesen** [FriendsOfSymfony/FOSUserBundle#2784]
**Symfony FOSUserBundle versions**:

```
symfony/symfony                          v3.4.8  The Symfony PHP framework
friendsofsymfony/user-bundle             v2.1.2  Symfony FOSUserBundle
```

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Install fos user bundle on Symfony 3.4 following manual
 2. Go to registration page
 3. Check logs

**Provide logs (if relevant)**:

`[2018-04-14 18:10:24] php.INFO: User Deprecated: The "fos_user.registration.form.type" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"fos_user.registration.form.type\" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. at /home/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:282)"} []`

routing.yml:
```
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
```

config.yml:
```
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "no-reply@domain.com"
        sender_name: "Domain No-Reply"
```

security.yml
```
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~
            form_login:
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret: '%secret%'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

```
