### ISSUE TITLE
Problem with afterlogin redirect url paremeter

### ISSUE THREAD

**Issue by etshy** [FriendsOfSymfony/FOSUserBundle#2789]
When I got logout after my session is done I'm redirected to /login (normal) and when I login I'm redirected to my previous page (still normal)
What's abnormal is that the redirectUrl is added to GET param again and again and again.
And I ended today with this URL `http://XXX.XXX.XXX.XXX/rapp/public/admin/chapter/edit/5ad52f6ade75341e60004755?_url=%2Fadmin%2Fchapter%2Fedit%2F5ad52f6ade75341e60004755&_url=%2Fadmin%2Fchapter%2Fedit%2F5ad52f6ade75341e60004755&_url=%2Fadmin%2Fchapter%2Fedit%2F5ad52f6ade75341e60004755&_url=%2Fadmin%2Fchapter%2Fedit%2F5ad52f6ade75341e60004755&_url=%2Fadmin%2Fchapter%2Fedit%2F5ad52f6ade75341e60004755`

Is there a way to prevent that `_url` parameter to show ?

**Comment by etshy** [comment]
Just had a response from a member of the Symfony repo [on this thread](https://github.com/symfony/symfony/issues/28605#issuecomment-424992936)

The answer explained my problem way better than I did, and seems it's a problem/misconfiguration here.

Here is my different configuration files about fosUser and routing

services.yaml
```
fos_user:
  db_driver: mongodb
  firewall_name: main
  user_class: App\Model\Document\User
  from_email:
    address: "%env(EMAIL_SENDER_ADDRESS)%"
    sender_name: "%env(EMAIL_SENDER_NAME)%"
  registration:
    confirmation:
      enabled: true
  profile:
    form:
      type: App\Form\Backend\Profile\ProfileFormType
```

security.yaml
```
security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

  encoders:
    FOS\UserBundle\Model\UserInterface:
      algorithm: argon2i
      memory_cost:          16384 # Amount in KiB. 16 MiB
      time_cost:            2 # Number of iterations
      threads:              4 # Number of parallel threads

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email

  firewalls:
    main:
      pattern: ^/
      form_login:
        provider: fos_userbundle
        csrf_token_generator: security.csrf.token_manager
        always_use_default_target_path: false
        default_target_path:            admin_profile_index
        use_referer: true
      logout:       true
      anonymous:    true
      remember_me:
        secret:   '%kernel.secret%'
        lifetime: 864000
        path:     /
        domain:   ~ # Defaults to the current domain from $_SERVER
```

routing.yaml
```
framework:
    router:
        strict_requirements: ~
```
