### ISSUE TITLE
Using event listener instead of overridding

### ISSUE THREAD

**Issue by devkbsc** [FriendsOfSymfony/FOSUserBundle#2821]
Hello, 
I have tried this eventlistener method to add my customisation code! 

**Symfony FOSUserBundle versions**: 

* SF - 3.4 
* FOS_USER - ~2.0

```
namespace UserBundle\EventListener;

use FOS\UserBundle\FOSUserEvents;
use FOS\UserBundle\Event\FormEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use UserBundle\Entity\User;
//use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class RegistrationListener implements EventSubscriberInterface{
    
    private $statut;
    
    public function __construct(User $user) {
        
        $em = $this->getDoctrine()->getManager();
        $default_statut = $em->getRepository('UserBundle:UserStatut')->find(4);
        $user->setUserStatut($default_statut);
        
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents() {
        return array(
            FOSUserEvents::REGISTRATION_SUCCESS => 'onRegistrationSuccess',
        );
    }
    
    public function onRegistrationSuccess(FormEvent $event){
        $dispatcher->dispatch(FOSUserEvents::REGISTRATION_INITIALIZE, new UserEvent($user, $request));
        $user = $event->getRequest();
        $event->setResponse($user);
        
    }
```

```
services:
    registration_success:
        class: UserBundle\EventListener\RegistrationListener
        arguments: ['@user']
        tags:
            - { name: kernel.event_subscriber }     
```
And it's not working 

![capture](https://user-images.githubusercontent.com/10415306/42885745-18c78d3a-8aa2-11e8-99e0-e6e4abfbba61.PNG)

did i missed or errored any part? Pls help me!! Not clear about the arguments i think!!
