### ISSUE TITLE
Provide documentation for Symfony4

### ISSUE THREAD

**Issue by polishExperiment** [FriendsOfSymfony/FOSUserBundle#2861]
This is feature request.  

Symfony 4.x  

Currently there is no documentation for Symfony 4.

This issue is an attempt at fixing that.

**Comment by polishExperiment** [comment]
Could someone put me as an assignee?
Could someone put a label `Documentation` or give me access to do that myself?

**Comment by XWB** [comment]
Feel free to open a pull request :)

**Comment by alfonsodev** [comment]
I've configured successfully the bundle in Symfony 4
the changes needed are 
- On `src/Entity/User.php` change the namespace form 
```
namespace AppBundle/User;
```
to
```
namespace App\Entity;
```
- The configuration needs to be in its own file
Create a new file called `config/packages/fos_user_bundle.yml` 
```
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User  # <--- Note the namespace must be App not AppBundle
    from_email:
        address: "%env(MAILER_ADDRESS)%"
        sender_name: "%env(MAILER_SENDER_NAME)%"
```
- On security.yml there is a problematic field
I had the same issue as #2855  so 
```
                user_checker: fos_user.user_checker
```
needs to be changed to
```
                user_checker: security.user_checker
```
seems to work after this change, but I'm not sure this is 100% correct
as @xabbuh points out in the below PR  `fos_user.user_checker` is still defined in security.yml file of the bundle.  
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2867
Also it would be needed to add a new element in the dropdown to point to version 4 
![image](https://user-images.githubusercontent.com/2131194/48097244-f78fe180-e221-11e8-8478-f26727639d0c.png) [on the Symfony documentation site](https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-5-configure-the-fosuserbundle)

**Comment by Clindbergh** [comment]
Also required:

You've to add the following to the `config/packages/framework.yaml`:

```yaml
framework:
    # ... other stuff ...
    
    templating:
        engines: ['twig', 'php']
```

_Originally posted by @devtronic in https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2870#issuecomment-441001037_
