### ISSUE TITLE
Do not send any email via Swiftmailer

### ISSUE THREAD

**Issue by GianlucaBergomi** [FriendsOfSymfony/FOSUserBundle#2894]
**Symfony FOSUserBundle version 2.1.2, Symfony 4.2.3**:

**Fos do not send any type of email. When, for example, I request the password resetting I do not receive any email but it's not a swiftmailer problem because it work properly in email sending**

Before the update to symfony 3 everything works properly.

This is my configuration:

```
#config/packages/fos_user.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\AppBundle\Entity\User
    from_email:
        address: "%env(USER_ADDRESS)%"
        sender_name: "%env(SENDER_NAME)%"
    registration:
        form:
            type: App\AppBundle\Form\RegistrationType
        confirmation:
            enabled: true
    service:
        mailer: fos_user.mailer.twig_swift
```

```
#config/packages/swifmailer.yaml
swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
```

```
#config/routes/fos_user.yaml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
```

Thank you in advance
