### ISSUE TITLE
configuration service mailer only use default service

### ISSUE THREAD

**Issue by zazoomauro** [FriendsOfSymfony/FOSUserBundle#2895]
**Symfony FOSUserBundle versions**:

symfony/* v4.2.3
api-platform/core v2.3.6
friendsofsymfony/user-bundle v2.1.2

**Description of the problem including expected versus actual behavior**:

I'm trying to use a custom mailer but is always using the default service `fos_user.mailer.default`.
Even if I try to use the service `fos_user.mailer.twig_swift`finally `fos_user.mailer.default` is used.
No way to use a different mailer service.

my `fos_user.yml`

```yaml
fos_user:
  ## Configuration
  db_driver: orm
  firewall_name: main

  user_class: App\Entity\User

  service:
    mailer: App\Service\Mailer
    # or mailer: 'fos_user.mailer.twig_swift'

  ## Mailing
  from_email:
    address: "noreply@..."
    sender_name: "..."
  registration:
    confirmation:
      enabled: true
      template: email/confirmation.twig

```
