### ISSUE TITLE
Can't Log in using default configuration 

### ISSUE THREAD

**Issue by KJee85** [FriendsOfSymfony/FOSUserBundle#392]
We are able to register and the user is created in the database but when attempting to login it just redirects back to the login page here are our config files:

security.yml:

``` yaml
security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:       fos_userbundle
            logout:
                path:           /logout
                target:         /
            anonymous:    true

        login:
            pattern: ^/login$
            security: false           

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
```

routing.yml

``` yaml
 Internal routing configuration to handle ESI
_internal:
   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
   prefix:   /_internal

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
```
