### ISSUE TITLE
Consider adding security checks

### ISSUE THREAD

**Issue by schmittjoh** [FriendsOfSymfony/FOSUserBundle#396]
Now, that there is support for expression-based authorization, I think it would make sense to let the user specify security checks for the controllers that are provided by this bundle.

``` yml
fos_user:
    access_control:
        login: isAnonymous()
```

This is also related to #393.
