### ISSUE TITLE
Emails not being sent via FOSUserBundle

### ISSUE THREAD

**Issue by codecowboy** [FriendsOfSymfony/FOSUserBundle#410]
I am having an issue with emails not being sent from FosUserBundle when a user registers (though the success message is displayed). I can do this in another controller:

``` php
<?php
  $message = \Swift_Message::newInstance()
        ->setSubject('Hello Email')
        ->setFrom('send@example.com')
        ->setTo('luke@lukem.co.uk')
        ->setBody('body of email')
    ;
    $this->get('mailer')->send($message);
```

And an email is added to the swiftmailer spool and sent correctly.

My fos_user config is here - https://gist.github.com/1376774 and my swiftmailer config is:

``` yaml
# Swiftmailer Configuration
swiftmailer:
    delivery_address:  luke@lukem.co.uk
    transport: gmail
    username:  admin@lukem.co.uk
    password:  XXXXXX
    spool:
        type: file
        path: %kernel.cache_dir%/swiftmailer/spool
    logging: %kernel.debug%
```

Nothing is written to dev.log or my php error log. ANy clue what might be going on here? Thanks!
