### ISSUE TITLE
Email or Username documentation not clear

### ISSUE THREAD

**Issue by OlivierCuyp** [FriendsOfSymfony/FOSUserBundle#476]
Hi,

I followed the installation instruction.
Then I created a UserBundle and tried to wrap the UserManager in another UserProvider as indicated on [Logging by Username or Email](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/logging_by_username_or_email.md).

In the security.yml file if I only put :

``` yml
...
providers:
        custom:
            id: dealecta_user.my_provider
...
```

I have this error message :

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                  
  The service "security.authentication.manager" has a dependency on a non-existent service "security.user.provider.concrete.fos_userbundle". 
```

But if I keep the original provider configuration, I have no more error :

``` yml
...
providers:
        custom:
            id: dealecta_user.my_provider
        fos_userbundle:
            id: fos_user.user_manager
...
```

I'm just not sure sure it is the right config or if I'm missing something.
