### ISSUE TITLE
Register/Login with email only

### ISSUE THREAD

**Issue by gavinwilliams** [FriendsOfSymfony/FOSUserBundle#555]
Is there any way to get FOSUserBundle to register/login by email only and disable/remove the username property?

**Comment by ry167** [comment]
@maxstekel, for this you also need to add the form type to `services.yml` as shown in [overriding_forms.md](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/overriding_forms.md)

```
# src/Acme/UserBundle/Resources/config/services.yml
services:
    acme_user.registration.form.type:
        class: Acme\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: acme_user_registration }
```

**Comment by bsaverino** [comment]
Is there anything wrong with overriding the User like this?  I know there is redundant info in the database but this should take care of all other situations correct? 
```
public function setEmail($email){
    $this->email = $email;
    $this->username = $email;
}

public function setEmailCanonical($emailCanonical){
    $this->emailCanonical = $emailCanonical;
    $this->usernameCanonical = $emailCanonical;
}
```

**Comment by merk** [comment]
We did this in one application but it ends up taking up 4 times as much space which can add up. We ended up implementing FOSUserBundle's UserInterface and manually mapped the fields we required instead.

**Comment by bsaverino** [comment]
I suppose it is 2 more fields than normal however 4 times as much space is shocking due to the nature of the data.  I'll keep that in mind, thanks for your input.

**Comment by merk** [comment]
Sorry, you're right - its only twice as much data, not 4 times as much - given the bundle stores a canonical representation of the email address already.

**Comment by heyalbert** [comment]
@MickL Is it possible to make a complete explanation what you did? For example the missing pieces Event/FormEvent.php and the Templates. That would be very great! So that we have a stable solution. Thank you. :-)

**Comment by heyalbert** [comment]
Ich followed the instructions from @MickL, @acidjames and @maxstekel, but I got into trouble:
```
  [Doctrine\ORM\Mapping\MappingException]
  Duplicate definition of column 'email' on entity 'AcmeBundle\Entity\User' in a field or discriminator column mapping.
```

What is the little thing I oversaw?

**Comment by clytemnestra** [comment]
Anyone found a solution to this?

**Comment by acidjames** [comment]
@clytemnestra the solution is in the thread replies

**Comment by heyalbert** [comment]
What about a clean solution, not something hacking together?

**Comment by clytemnestra** [comment]
Well there are problems with those ideas.

First of all, FOSUserManager has both username and email address in its UserInterface, so the entire manager needs to be rewritten. Second of all, there's 3 unnecessary bonus fields in the DB instead of just 1. This represents problems with big databases.

**Comment by lakhman** [comment]
Related link:

http://stackoverflow.com/questions/8832916/remove-replace-the-username-field-with-email-using-fosuserbundle-in-symfony2/21064627#21064627

**Comment by StijnVrolijk** [comment]
I recently had the same issue but I had no option to put the email in the username.
I created a solution that purely finds a user by checking the actual email property.

1. Create a service instance of the EntityUserProvider
```
  acme_user_bundle.user_provider.acme_user:
    class: Symfony\Bridge\Doctrine\Security\User\EntityUserProvider
    arguments:
      - "@doctrine"
      - Acme\UserBundle\Entity\AcmeUser
      - "email"
```

2. Register your provider in `security.yml`
```
security:
  providers:
    chain_provider:
      chain:
        providers: [email_only_provider]
    email_only_provider:
      id: acme_user_bundle.user_provider.acme_user
```

And that's it, you're logging in by email.
