### ISSUE TITLE
Problem with Overriding_forms

### ISSUE THREAD

**Issue by Chrysweel** [FriendsOfSymfony/FOSUserBundle#644]
Hello! 

I have Symfony 2.0.14 and FOSUserBundle 1.2.0

I overried the RegistrationFormType.php in order to add a name field like this ( I followed this article: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/1.2.0/Resources/doc/overriding_forms.md ):

``` php
<?php

namespace sdfs\sdfsBundle\Form\Type;

use Symfony\Component\Form\FormBuilderInterface;
use FOS\UserBundle\Form\Type\RegistrationFormType as BaseType;

class RegistrationFormType extends BaseType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        // add your custom field
        $builder->add('name');
    }

    public function getName()
    {
        return 'sdfs_user_registration';
    }
}
```

My Services.yml in sdfs/sdfsBundle/Resources/config/services.yml:

``` yaml
services:
    sdfs_user.registration.form.type:
        class: sdfs\sdfsBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sdfs_user_registration }
    sdfs_user.form.handler.registration:
        class: sdfs\sdfsBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer"]
        scope: request
        public: false
```

And my config.yml in app/config/config.yml:

``` yaml
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: sdfs\sdfsBundle\Entity\User

    registration:
        form:
            type: sdfs_user_registration
            handler: sdfs_user.form.handler.registration
```

But I have the following error: 

ParseException: Indentation problem in "\/var\/www\/sdfs\/src\/sdfs\/sdfsBundle\/DependencyInjection\/..\/Resources\/config\/services.yml" at line 15 (near " sdfs_user.registration.form.type:").

Any Idea please???? 
THANKS!
