### ISSUE TITLE
Multiple user providers

### ISSUE THREAD

**Issue by xmateos** [FriendsOfSymfony/FOSUserBundle#745]
Hi there,

I´ve got 2 entities extending BaseUser (from FOSUserBundle), since I need 2 user managers (frontend, backend).

I´ve recreated service from ORM.XML into my second bundle, as well as created the new user provider in security.yml, but I must be doing something wrong, since my "backend" user provider still tries to find the login credentials in the first user provider.

-> added to "orm.xml" (from FOSUserBundle)

```
<service id="fos_user.user_manager.admin" class="FOS\UserBundle\Entity\UserManager" public="false">
    <argument type="service" id="security.encoder_factory" />
    <argument type="service" id="fos_user.util.username_canonicalizer" />
    <argument type="service" id="fos_user.util.email_canonicalizer" />
    <argument type="service" id="fos_user.entity_manager" />
    <argument>SRC\AdminBundle\Entity\Admin</argument>
</service>
```

-> app/config/security.yml

```
providers:
    fos_userbundle:
        id: fos_user.user_manager
    fos_adminbundle:
        id: fos_user.user_manager.admin

firewalls:
    main:
        pattern:    ^/
        form_login:
            check_path: /user/login_check
            login_path: /user/login
            provider: fos_userbundle
        logout:
            path:   /user/logout
            target: /
        anonymous: ~

    admin:
        pattern:    ^/admin
        form_login:
            check_path: /admin/login_check
            login_path: /admin/login
            provider: fos_adminbundle
        logout:
            path:   /admin/logout
```

Could you please give me a few pointers on how to get this working?

Thank you very much.
