### ISSUE TITLE
Could not load type "fos_user_change_password_form"

### ISSUE THREAD

**Issue by Stefun** [FriendsOfSymfony/FOSUserBundle#798]
I have followed the instructions on FOSUserBundle installation. I'm using symfony 2.0 and FOSUserBundle locked to 1.2.0 as suggested in  Issue #643 . Before i used to get different error because version was not compatible with symfony2 but changepassword was working fine that time. So i locked to FOSUB to 1.2.0.  No when I'm trying to access profile.change-password I'm getting error like

Could not load type "fos_user_change_password_form"

in Config.yml file i have

``` yml
 change_password:
        form:
            type:               fos_user_change_password
            handler:            fos_user.change_password.form.handler.default
            name:               fos_user_change_password_form
            validation_groups:  [ChangePassword]  
```

Any suggestions? Again any compatible issue?
