### ISSUE TITLE
Custom session not used and error on login

### ISSUE THREAD

**Issue by michelpa** [FriendsOfSymfony/FOSUserBundle#802]
Hello,

I've set a custom session with the definition of a service. Then in config.yml set 

```
framework:
        ...
   session:
        handler_id: session.handler.memcache
```

And now on login_check, I've got an error
Call to a member function getMessage() on a non-object on $error = $error->getMessage();

This is because the controller does not access to my session and then cannot retrieve datas.

Any idea on how to fix it?

Thanks
