### ISSUE TITLE
Is there a way to have a login form for admin and a login form for all other users?

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSUserBundle#849]
Ok i know is more a question as an issue :-) sorry for that.

The problem is i have a backend and a frontend and this have different login forms/styles.

i go to (/admincp) and i need the login form for an admin if not logged in.

and the user on the frontend (/login) will see a login form that passes the styles on the frontend...

Sorry for my english but i hope someone understands me.

Thanks and sorry for an question on a issue :-)

**Comment by neetunayak** [comment]
How should I add custom css for this login page?

**Comment by vicks1** [comment]
How should I add custom css for this login page, I need to add bootstrap css for it.

**Comment by topwebstudio** [comment]
Override FOSUserBundle template, it's easy

**Comment by armnit** [comment]
Hi, I am on Symfony 3.2 and I have got the following error message when I try to implement the solution of topwebstudio :

You have requested a non-existent service "request". Did you mean one of these: "data_collector.request", "monolog.logger.request", "request_stack", "router.request_context", "validate_request_listener"?

The service "request" has been replaced ?

**Comment by WickedSilver** [comment]
This is for as far as i know not a FOSUserBundle question but a Symfony question.
But i'd suggest looking at [this](http://stackoverflow.com/questions/41361267/how-can-i-fix-request-service-is-deprecated-in-symfony2-version-2-8) stack overflow article.

The "request" service has been deprecated for a while now and has been removed starting from symfony 3.0

**Comment by somoza** [comment]
In 3.0 or highers versions replace this line on controller:

`$requestAttributes = $this->container->get('request')->attributes;`

By:

`$requestAttributes = $this->container->get('request_stack')->getCurrentRequest();`

And the routing.yml for >= 3.0 is:

```
admin_login:
    path:  /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }

admin_check:
    path:  /admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

admin_logout:
    path:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }
```
