### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by vazgen** [FriendsOfSymfony/FOSUserBundle#883]
Hi, there is a strange error and I am not sure that it is related to FOSUserBundle (I guess it might be related to symfony form). But anyway let me tell about it.

There was a need to make my own validation logic for registration form. So  I guess this can be helpfull for others to.

I have made my own registration form that does not have double password, only single filed that has validation at least 6 letters.

```
public function buildForm(FormBuilderInterface $builder, array $options)
{
     $builder->add('email', 'email', array('label' => 'form.email', 'translation_domain' => 'FOSUserBundle'))
        ->add('firstname')
        ->add('plainPassword', 'password')
        ->add('agree', 'checkbox', array());
}
```

also I have made validation.yml

```
XXX\UserBundle\Entity\User:
 constraints:
       - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
properties:
    email:
      - Email: { groups: [Registration] }
plainPassword:
  - NotBlank: { groups: [Registration] }
  - MinLength: { limit: 6, message: "fos_user.plainPassword.length" }
firstname:
  - NotBlank: { groups: [Registration] }
  - MinLength: { limit: 2, message: "Your first name must have at least {{ limit }} characters" }
```

so when I fill data to the fields and submit the form I have to see error messages. Here is the problem:

if I use "{{form_errors(form)}}" it does not print any error, but if I use "{{form_errors(form.plainPassword)}} " it shows error "Your password must have at least 6 characters"
