### ISSUE TITLE
Unrecognized options "handler" under "fos_user.registration.form"

### ISSUE THREAD

**Issue by gchokeen** [FriendsOfSymfony/FOSUserBundle#928]
After upgrade I got this error. I understand you removed handler and using new method **EventListeners** from this [answer](http://stackoverflow.com/a/14124021/430112). But now I have few questions.

**My FOS Configuration:**

```
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Acme\UserBundle\Entity\User
    group:
        group_class: Acme\UserBundle\Entity\Group
    registration:
        form:
            handler: acme_user.form.handler.registration
            type: acme_user_registration
```

I basically overrides FOS registration handler from acme user bundle, to add role on success event as below.

```
    protected function onSuccess(UserInterface $user, $confirmation)
    {
         $data = $this->form->get('role')->getData();

         $user->addRole( $data );

        parent::onSuccess($user, $confirmation);

    }

```

Now how can I override the event Listener to do the same task. 

**Another question**  
           I am using AcmeUserBundle upto now for extending and managing user entities. Now I am trying to install Sonataadminbundle. So it's required another userbundle called **SonataUserBundle** with FOSUserBundle.      What Should I do now, Should I drop AcmeUserBundle or can I manage both. Advice me please !

So the error I am getting 

```
LogicException: Bundle "FOSUserBundle" is directly extended by two bundles "SonataUserBundle" and "AcmeUserBundle"

```
