### ISSUE TITLE
FOSUserBundle RegistrationFormType overwride Could not load type

### ISSUE THREAD

**Issue by aymen2255** [FriendsOfSymfony/FOSUserBundle#985]
hi 
I would like to add some new fileds to registration form, but don't
wont to change RegistrationFormType directly in FOSUserBundle
so trying to overwride it through app/config/config.yml 

``` yaml
fos_user:
    # ...
    registration:
        form:
            type: Worldwar_user_registration
```

and src/Worldwar/UserBundle/Resources/config/services.yml

``` yaml
services:
    Worldwar_user_registration:
        class: Worldwar\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: Worldwar_user_registration }
```

but error occurs:
 Could not load type "Worldwar_user_registration" 
 i am trying to change Worldwar_user_registration by Worldwar\UserBundle\Form\Type\RegistrationFormType but i have the same error
what's wrong?
